//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace IntegracionITGF.ITGFDataModel
{

    public partial class INT_CR_INF_LABORALES : XPLiteObject
    {
        string fCOD_PERSONA;
        [Size(10)]
        public string COD_PERSONA
        {
            get { return fCOD_PERSONA; }
            set { SetPropertyValue<string>(nameof(COD_PERSONA), ref fCOD_PERSONA, value); }
        }
        short? fNRO_SECUENCIA;
        public short? NRO_SECUENCIA
        {
            get { return fNRO_SECUENCIA; }
            set { SetPropertyValue<short?>(nameof(NRO_SECUENCIA), ref fNRO_SECUENCIA, value); }
        }
        string fLUG_TRABAJO;
        [Size(120)]
        public string LUG_TRABAJO
        {
            get { return fLUG_TRABAJO; }
            set { SetPropertyValue<string>(nameof(LUG_TRABAJO), ref fLUG_TRABAJO, value); }
        }
        DateTime fFEC_INGRESO;
        public DateTime FEC_INGRESO
        {
            get { return fFEC_INGRESO; }
            set { SetPropertyValue<DateTime>(nameof(FEC_INGRESO), ref fFEC_INGRESO, value); }
        }
        DateTime fFEC_SALIDA;
        public DateTime FEC_SALIDA
        {
            get { return fFEC_SALIDA; }
            set { SetPropertyValue<DateTime>(nameof(FEC_SALIDA), ref fFEC_SALIDA, value); }
        }
        decimal? fMTO_INGRESO;
        [ColumnDbDefaultValue("0 ")]
        public decimal? MTO_INGRESO
        {
            get { return fMTO_INGRESO; }
            set { SetPropertyValue<decimal?>(nameof(MTO_INGRESO), ref fMTO_INGRESO, value); }
        }
        string fCOD_MONEDA;
        [Size(3)]
        public string COD_MONEDA
        {
            get { return fCOD_MONEDA; }
            set { SetPropertyValue<string>(nameof(COD_MONEDA), ref fCOD_MONEDA, value); }
        }
        string fDES_PUESTO;
        [Size(80)]
        public string DES_PUESTO
        {
            get { return fDES_PUESTO; }
            set { SetPropertyValue<string>(nameof(DES_PUESTO), ref fDES_PUESTO, value); }
        }
        string fTIP_CARGO;
        [Size(1)]
        [ColumnDbDefaultValue("'E'")]
        public string TIP_CARGO
        {
            get { return fTIP_CARGO; }
            set { SetPropertyValue<string>(nameof(TIP_CARGO), ref fTIP_CARGO, value); }
        }
        byte? fTIP_INGRESO;
        public byte? TIP_INGRESO
        {
            get { return fTIP_INGRESO; }
            set { SetPropertyValue<byte?>(nameof(TIP_INGRESO), ref fTIP_INGRESO, value); }
        }
        string fACTUAL;
        [Size(1)]
        public string ACTUAL
        {
            get { return fACTUAL; }
            set { SetPropertyValue<string>(nameof(ACTUAL), ref fACTUAL, value); }
        }
        string fTIP_EMPLEO;
        [Size(1)]
        public string TIP_EMPLEO
        {
            get { return fTIP_EMPLEO; }
            set { SetPropertyValue<string>(nameof(TIP_EMPLEO), ref fTIP_EMPLEO, value); }
        }
        byte? fCOD_RAMO;
        public byte? COD_RAMO
        {
            get { return fCOD_RAMO; }
            set { SetPropertyValue<byte?>(nameof(COD_RAMO), ref fCOD_RAMO, value); }
        }
        string fOBSERVACION;
        [Size(1000)]
        public string OBSERVACION
        {
            get { return fOBSERVACION; }
            set { SetPropertyValue<string>(nameof(OBSERVACION), ref fOBSERVACION, value); }
        }
        byte? fCOD_DIRECCION;
        public byte? COD_DIRECCION
        {
            get { return fCOD_DIRECCION; }
            set { SetPropertyValue<byte?>(nameof(COD_DIRECCION), ref fCOD_DIRECCION, value); }
        }
        byte? fCOD_TELEFONO;
        public byte? COD_TELEFONO
        {
            get { return fCOD_TELEFONO; }
            set { SetPropertyValue<byte?>(nameof(COD_TELEFONO), ref fCOD_TELEFONO, value); }
        }
        string fDIR_CORREO;
        [Size(80)]
        public string DIR_CORREO
        {
            get { return fDIR_CORREO; }
            set { SetPropertyValue<string>(nameof(DIR_CORREO), ref fDIR_CORREO, value); }
        }
        string fNOM_PER_CONTACTO;
        [Size(120)]
        public string NOM_PER_CONTACTO
        {
            get { return fNOM_PER_CONTACTO; }
            set { SetPropertyValue<string>(nameof(NOM_PER_CONTACTO), ref fNOM_PER_CONTACTO, value); }
        }
        string fUSU_INSERCION;
        [Size(10)]
        [ColumnDbDefaultValue("SUBSTR(USER,1,10) ")]
        public string USU_INSERCION
        {
            get { return fUSU_INSERCION; }
            set { SetPropertyValue<string>(nameof(USU_INSERCION), ref fUSU_INSERCION, value); }
        }
        DateTime fFEC_INSERCION;
        [ColumnDbDefaultValue("SYSDATE ")]
        public DateTime FEC_INSERCION
        {
            get { return fFEC_INSERCION; }
            set { SetPropertyValue<DateTime>(nameof(FEC_INSERCION), ref fFEC_INSERCION, value); }
        }
        string fUSU_MODIFICACION;
        [Size(10)]
        [ColumnDbDefaultValue("SUBSTR(USER,1,10) ")]
        public string USU_MODIFICACION
        {
            get { return fUSU_MODIFICACION; }
            set { SetPropertyValue<string>(nameof(USU_MODIFICACION), ref fUSU_MODIFICACION, value); }
        }
        DateTime fFEC_MODIFICACION;
        [ColumnDbDefaultValue("SYSDATE ")]
        public DateTime FEC_MODIFICACION
        {
            get { return fFEC_MODIFICACION; }
            set { SetPropertyValue<DateTime>(nameof(FEC_MODIFICACION), ref fFEC_MODIFICACION, value); }
        }
        string fID_PERSONA;
        [Size(36)]
        public string ID_PERSONA
        {
            get { return fID_PERSONA; }
            set { SetPropertyValue<string>(nameof(ID_PERSONA), ref fID_PERSONA, value); }
        }
        string fID_INFO_LABORAL;
        [Size(36)]
        public string ID_INFO_LABORAL
        {
            get { return fID_INFO_LABORAL; }
            set { SetPropertyValue<string>(nameof(ID_INFO_LABORAL), ref fID_INFO_LABORAL, value); }
        }
        string fOID;
        [Key]
        [Size(36)]
        public string OID
        {
            get { return fOID; }
            set { SetPropertyValue<string>(nameof(OID), ref fOID, value); }
        }
        string fPROCESADO;
        [Size(1)]
        public string PROCESADO
        {
            get { return fPROCESADO; }
            set { SetPropertyValue<string>(nameof(PROCESADO), ref fPROCESADO, value); }
        }
    }

}
