//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace IntegracionITGF.ITGFDataModel
{

    public partial class INT_CR_REF_PERSONALES : XPLiteObject
    {
        string fCOD_PERSONA;
        [Size(10)]
        public string COD_PERSONA
        {
            get { return fCOD_PERSONA; }
            set { SetPropertyValue<string>(nameof(COD_PERSONA), ref fCOD_PERSONA, value); }
        }
        short? fCOD_REFERENCIA;
        public short? COD_REFERENCIA
        {
            get { return fCOD_REFERENCIA; }
            set { SetPropertyValue<short?>(nameof(COD_REFERENCIA), ref fCOD_REFERENCIA, value); }
        }
        string fTIP_REFERENCIA;
        [Size(1)]
        public string TIP_REFERENCIA
        {
            get { return fTIP_REFERENCIA; }
            set { SetPropertyValue<string>(nameof(TIP_REFERENCIA), ref fTIP_REFERENCIA, value); }
        }
        short? fNRO_SECUENCIA;
        public short? NRO_SECUENCIA
        {
            get { return fNRO_SECUENCIA; }
            set { SetPropertyValue<short?>(nameof(NRO_SECUENCIA), ref fNRO_SECUENCIA, value); }
        }
        string fNOM_PERSONA;
        [Size(80)]
        public string NOM_PERSONA
        {
            get { return fNOM_PERSONA; }
            set { SetPropertyValue<string>(nameof(NOM_PERSONA), ref fNOM_PERSONA, value); }
        }
        string fTELEFONOS;
        [Size(20)]
        public string TELEFONOS
        {
            get { return fTELEFONOS; }
            set { SetPropertyValue<string>(nameof(TELEFONOS), ref fTELEFONOS, value); }
        }
        string fLUG_TRABAJO;
        [Size(80)]
        public string LUG_TRABAJO
        {
            get { return fLUG_TRABAJO; }
            set { SetPropertyValue<string>(nameof(LUG_TRABAJO), ref fLUG_TRABAJO, value); }
        }
        string fPUESTO;
        [Size(80)]
        public string PUESTO
        {
            get { return fPUESTO; }
            set { SetPropertyValue<string>(nameof(PUESTO), ref fPUESTO, value); }
        }
        string fREL_PERSONA;
        [Size(30)]
        public string REL_PERSONA
        {
            get { return fREL_PERSONA; }
            set { SetPropertyValue<string>(nameof(REL_PERSONA), ref fREL_PERSONA, value); }
        }
        string fUSU_INSERCION;
        [Size(10)]
        [ColumnDbDefaultValue("SUBSTR(USER,1,10) ")]
        public string USU_INSERCION
        {
            get { return fUSU_INSERCION; }
            set { SetPropertyValue<string>(nameof(USU_INSERCION), ref fUSU_INSERCION, value); }
        }
        DateTime fFEC_INSERCION;
        [ColumnDbDefaultValue("SYSDATE ")]
        public DateTime FEC_INSERCION
        {
            get { return fFEC_INSERCION; }
            set { SetPropertyValue<DateTime>(nameof(FEC_INSERCION), ref fFEC_INSERCION, value); }
        }
        string fUSU_MODIFICACION;
        [Size(10)]
        [ColumnDbDefaultValue("SUBSTR(USER,1,10) ")]
        public string USU_MODIFICACION
        {
            get { return fUSU_MODIFICACION; }
            set { SetPropertyValue<string>(nameof(USU_MODIFICACION), ref fUSU_MODIFICACION, value); }
        }
        DateTime fFEC_MODIFICACION;
        [ColumnDbDefaultValue("SYSDATE ")]
        public DateTime FEC_MODIFICACION
        {
            get { return fFEC_MODIFICACION; }
            set { SetPropertyValue<DateTime>(nameof(FEC_MODIFICACION), ref fFEC_MODIFICACION, value); }
        }
        string fOBSERVACION;
        [Size(1000)]
        public string OBSERVACION
        {
            get { return fOBSERVACION; }
            set { SetPropertyValue<string>(nameof(OBSERVACION), ref fOBSERVACION, value); }
        }
        string fEST_VERIFICACION;
        [Size(1)]
        [ColumnDbDefaultValue("'N'")]
        public string EST_VERIFICACION
        {
            get { return fEST_VERIFICACION; }
            set { SetPropertyValue<string>(nameof(EST_VERIFICACION), ref fEST_VERIFICACION, value); }
        }
        string fCONOCE;
        [Size(1)]
        [ColumnDbDefaultValue("'N'")]
        public string CONOCE
        {
            get { return fCONOCE; }
            set { SetPropertyValue<string>(nameof(CONOCE), ref fCONOCE, value); }
        }
        string fREC_MENSAJE;
        [Size(1)]
        [ColumnDbDefaultValue("'N'")]
        public string REC_MENSAJE
        {
            get { return fREC_MENSAJE; }
            set { SetPropertyValue<string>(nameof(REC_MENSAJE), ref fREC_MENSAJE, value); }
        }
        string fCNF_DAT_PARTICULARES;
        [Size(1)]
        [ColumnDbDefaultValue("'N'")]
        public string CNF_DAT_PARTICULARES
        {
            get { return fCNF_DAT_PARTICULARES; }
            set { SetPropertyValue<string>(nameof(CNF_DAT_PARTICULARES), ref fCNF_DAT_PARTICULARES, value); }
        }
        string fCNF_DAT_LABORALES;
        [Size(1)]
        [ColumnDbDefaultValue("'N'")]
        public string CNF_DAT_LABORALES
        {
            get { return fCNF_DAT_LABORALES; }
            set { SetPropertyValue<string>(nameof(CNF_DAT_LABORALES), ref fCNF_DAT_LABORALES, value); }
        }
        string fCOD_USU_VERIFICADOR;
        [Size(10)]
        public string COD_USU_VERIFICADOR
        {
            get { return fCOD_USU_VERIFICADOR; }
            set { SetPropertyValue<string>(nameof(COD_USU_VERIFICADOR), ref fCOD_USU_VERIFICADOR, value); }
        }
        string fOBS_VERIFICACION;
        [Size(1000)]
        public string OBS_VERIFICACION
        {
            get { return fOBS_VERIFICACION; }
            set { SetPropertyValue<string>(nameof(OBS_VERIFICACION), ref fOBS_VERIFICACION, value); }
        }
        DateTime fFEC_VERIFICACION;
        public DateTime FEC_VERIFICACION
        {
            get { return fFEC_VERIFICACION; }
            set { SetPropertyValue<DateTime>(nameof(FEC_VERIFICACION), ref fFEC_VERIFICACION, value); }
        }
        short? fCOD_INF_LABORAL;
        public short? COD_INF_LABORAL
        {
            get { return fCOD_INF_LABORAL; }
            set { SetPropertyValue<short?>(nameof(COD_INF_LABORAL), ref fCOD_INF_LABORAL, value); }
        }
        string fNOM_PER_INFORMO;
        [Size(120)]
        public string NOM_PER_INFORMO
        {
            get { return fNOM_PER_INFORMO; }
            set { SetPropertyValue<string>(nameof(NOM_PER_INFORMO), ref fNOM_PER_INFORMO, value); }
        }
        string fCAR_PER_INFORMO;
        [Size(35)]
        public string CAR_PER_INFORMO
        {
            get { return fCAR_PER_INFORMO; }
            set { SetPropertyValue<string>(nameof(CAR_PER_INFORMO), ref fCAR_PER_INFORMO, value); }
        }
        string fNOM_PER_CERTIFICO;
        [Size(120)]
        public string NOM_PER_CERTIFICO
        {
            get { return fNOM_PER_CERTIFICO; }
            set { SetPropertyValue<string>(nameof(NOM_PER_CERTIFICO), ref fNOM_PER_CERTIFICO, value); }
        }
        string fCAR_PER_CERTIFICO;
        [Size(35)]
        public string CAR_PER_CERTIFICO
        {
            get { return fCAR_PER_CERTIFICO; }
            set { SetPropertyValue<string>(nameof(CAR_PER_CERTIFICO), ref fCAR_PER_CERTIFICO, value); }
        }
        string fID_PERSONA;
        [Size(36)]
        public string ID_PERSONA
        {
            get { return fID_PERSONA; }
            set { SetPropertyValue<string>(nameof(ID_PERSONA), ref fID_PERSONA, value); }
        }
        string fOID;
        [Key]
        [Size(36)]
        public string OID
        {
            get { return fOID; }
            set { SetPropertyValue<string>(nameof(OID), ref fOID, value); }
        }
        string fID_REFERENCIA;
        [Size(36)]
        public string ID_REFERENCIA
        {
            get { return fID_REFERENCIA; }
            set { SetPropertyValue<string>(nameof(ID_REFERENCIA), ref fID_REFERENCIA, value); }
        }
        string fPROCESADO;
        [Size(1)]
        [ColumnDbDefaultValue("'N'\n")]
        public string PROCESADO
        {
            get { return fPROCESADO; }
            set { SetPropertyValue<string>(nameof(PROCESADO), ref fPROCESADO, value); }
        }
    }

}
