//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace IntegracionITGF.ITGFDataModel
{

    public partial class INT_CR_REF_COMERCIALES : XPLiteObject
    {
        string fID_PERSONA;
        [Size(36)]
        public string ID_PERSONA
        {
            get { return fID_PERSONA; }
            set { SetPropertyValue<string>(nameof(ID_PERSONA), ref fID_PERSONA, value); }
        }
        string fOID;
        [Key]
        [Size(36)]
        public string OID
        {
            get { return fOID; }
            set { SetPropertyValue<string>(nameof(OID), ref fOID, value); }
        }
        string fID_REFERENCIA;
        [Size(36)]
        public string ID_REFERENCIA
        {
            get { return fID_REFERENCIA; }
            set { SetPropertyValue<string>(nameof(ID_REFERENCIA), ref fID_REFERENCIA, value); }
        }
        string fPROCESADO;
        [Size(1)]
        [ColumnDbDefaultValue("'N'\n")]
        public string PROCESADO
        {
            get { return fPROCESADO; }
            set { SetPropertyValue<string>(nameof(PROCESADO), ref fPROCESADO, value); }
        }
        string fCOD_PERSONA;
        [Size(10)]
        public string COD_PERSONA
        {
            get { return fCOD_PERSONA; }
            set { SetPropertyValue<string>(nameof(COD_PERSONA), ref fCOD_PERSONA, value); }
        }
        bool fCOD_REFERENCIA;
        public bool COD_REFERENCIA
        {
            get { return fCOD_REFERENCIA; }
            set { SetPropertyValue<bool>(nameof(COD_REFERENCIA), ref fCOD_REFERENCIA, value); }
        }
        string fTIP_REFERENCIA;
        [Size(1)]
        public string TIP_REFERENCIA
        {
            get { return fTIP_REFERENCIA; }
            set { SetPropertyValue<string>(nameof(TIP_REFERENCIA), ref fTIP_REFERENCIA, value); }
        }
        short fNRO_SECUENCIA;
        public short NRO_SECUENCIA
        {
            get { return fNRO_SECUENCIA; }
            set { SetPropertyValue<short>(nameof(NRO_SECUENCIA), ref fNRO_SECUENCIA, value); }
        }
        string fDES_ENTIDAD;
        [Size(50)]
        public string DES_ENTIDAD
        {
            get { return fDES_ENTIDAD; }
            set { SetPropertyValue<string>(nameof(DES_ENTIDAD), ref fDES_ENTIDAD, value); }
        }
        byte? fCOD_TIP_CUENTA;
        public byte? COD_TIP_CUENTA
        {
            get { return fCOD_TIP_CUENTA; }
            set { SetPropertyValue<byte?>(nameof(COD_TIP_CUENTA), ref fCOD_TIP_CUENTA, value); }
        }
        string fNRO_CUENTA;
        [Size(15)]
        public string NRO_CUENTA
        {
            get { return fNRO_CUENTA; }
            set { SetPropertyValue<string>(nameof(NRO_CUENTA), ref fNRO_CUENTA, value); }
        }
        string fCOD_MONEDA;
        [Size(3)]
        public string COD_MONEDA
        {
            get { return fCOD_MONEDA; }
            set { SetPropertyValue<string>(nameof(COD_MONEDA), ref fCOD_MONEDA, value); }
        }
        decimal fVAL_CREDITO;
        [ColumnDbDefaultValue("0")]
        public decimal VAL_CREDITO
        {
            get { return fVAL_CREDITO; }
            set { SetPropertyValue<decimal>(nameof(VAL_CREDITO), ref fVAL_CREDITO, value); }
        }
        decimal fSAL_CREDITO;
        [ColumnDbDefaultValue("0")]
        public decimal SAL_CREDITO
        {
            get { return fSAL_CREDITO; }
            set { SetPropertyValue<decimal>(nameof(SAL_CREDITO), ref fSAL_CREDITO, value); }
        }
        decimal fVAL_CUOTA;
        [ColumnDbDefaultValue("0")]
        public decimal VAL_CUOTA
        {
            get { return fVAL_CUOTA; }
            set { SetPropertyValue<decimal>(nameof(VAL_CUOTA), ref fVAL_CUOTA, value); }
        }
        DateTime fFEC_APERTURA;
        public DateTime FEC_APERTURA
        {
            get { return fFEC_APERTURA; }
            set { SetPropertyValue<DateTime>(nameof(FEC_APERTURA), ref fFEC_APERTURA, value); }
        }
        DateTime fFEC_VENCIMIENTO;
        public DateTime FEC_VENCIMIENTO
        {
            get { return fFEC_VENCIMIENTO; }
            set { SetPropertyValue<DateTime>(nameof(FEC_VENCIMIENTO), ref fFEC_VENCIMIENTO, value); }
        }
        string fDES_GARANTIA;
        [Size(160)]
        public string DES_GARANTIA
        {
            get { return fDES_GARANTIA; }
            set { SetPropertyValue<string>(nameof(DES_GARANTIA), ref fDES_GARANTIA, value); }
        }
        string fUSU_INSERCION;
        [Size(10)]
        [ColumnDbDefaultValue("SUBSTR(USER,1,10) ")]
        public string USU_INSERCION
        {
            get { return fUSU_INSERCION; }
            set { SetPropertyValue<string>(nameof(USU_INSERCION), ref fUSU_INSERCION, value); }
        }
        DateTime fFEC_INSERCION;
        [ColumnDbDefaultValue("SYSDATE ")]
        public DateTime FEC_INSERCION
        {
            get { return fFEC_INSERCION; }
            set { SetPropertyValue<DateTime>(nameof(FEC_INSERCION), ref fFEC_INSERCION, value); }
        }
        string fUSU_MODIFICACION;
        [Size(10)]
        [ColumnDbDefaultValue("SUBSTR(USER,1,10) ")]
        public string USU_MODIFICACION
        {
            get { return fUSU_MODIFICACION; }
            set { SetPropertyValue<string>(nameof(USU_MODIFICACION), ref fUSU_MODIFICACION, value); }
        }
        DateTime fFEC_MODIFICACION;
        [ColumnDbDefaultValue("SYSDATE ")]
        public DateTime FEC_MODIFICACION
        {
            get { return fFEC_MODIFICACION; }
            set { SetPropertyValue<DateTime>(nameof(FEC_MODIFICACION), ref fFEC_MODIFICACION, value); }
        }
        string fOBSERVACION;
        [Size(1000)]
        public string OBSERVACION
        {
            get { return fOBSERVACION; }
            set { SetPropertyValue<string>(nameof(OBSERVACION), ref fOBSERVACION, value); }
        }
        short? fCOD_ENTE;
        public short? COD_ENTE
        {
            get { return fCOD_ENTE; }
            set { SetPropertyValue<short?>(nameof(COD_ENTE), ref fCOD_ENTE, value); }
        }
        string fTELEFONO;
        [Size(10)]
        public string TELEFONO
        {
            get { return fTELEFONO; }
            set { SetPropertyValue<string>(nameof(TELEFONO), ref fTELEFONO, value); }
        }
        string fEST_VERIFICACION;
        [Size(1)]
        [ColumnDbDefaultValue("'N' ")]
        public string EST_VERIFICACION
        {
            get { return fEST_VERIFICACION; }
            set { SetPropertyValue<string>(nameof(EST_VERIFICACION), ref fEST_VERIFICACION, value); }
        }
        string fCOD_USU_VERIFICADOR;
        [Size(10)]
        public string COD_USU_VERIFICADOR
        {
            get { return fCOD_USU_VERIFICADOR; }
            set { SetPropertyValue<string>(nameof(COD_USU_VERIFICADOR), ref fCOD_USU_VERIFICADOR, value); }
        }
        string fOBS_VERIFICACION;
        [Size(1000)]
        public string OBS_VERIFICACION
        {
            get { return fOBS_VERIFICACION; }
            set { SetPropertyValue<string>(nameof(OBS_VERIFICACION), ref fOBS_VERIFICACION, value); }
        }
        DateTime fFEC_VERIFICACION;
        public DateTime FEC_VERIFICACION
        {
            get { return fFEC_VERIFICACION; }
            set { SetPropertyValue<DateTime>(nameof(FEC_VERIFICACION), ref fFEC_VERIFICACION, value); }
        }
        short fCAN_CUOTAS;
        public short CAN_CUOTAS
        {
            get { return fCAN_CUOTAS; }
            set { SetPropertyValue<short>(nameof(CAN_CUOTAS), ref fCAN_CUOTAS, value); }
        }
        short fCAN_PAGADAS;
        public short CAN_PAGADAS
        {
            get { return fCAN_PAGADAS; }
            set { SetPropertyValue<short>(nameof(CAN_PAGADAS), ref fCAN_PAGADAS, value); }
        }
        decimal fMTO_LINEA;
        [ColumnDbDefaultValue("0")]
        public decimal MTO_LINEA
        {
            get { return fMTO_LINEA; }
            set { SetPropertyValue<decimal>(nameof(MTO_LINEA), ref fMTO_LINEA, value); }
        }
        decimal fMTO_MENSUAL;
        [ColumnDbDefaultValue("0")]
        public decimal MTO_MENSUAL
        {
            get { return fMTO_MENSUAL; }
            set { SetPropertyValue<decimal>(nameof(MTO_MENSUAL), ref fMTO_MENSUAL, value); }
        }
        short fMAX_ATRASO;
        public short MAX_ATRASO
        {
            get { return fMAX_ATRASO; }
            set { SetPropertyValue<short>(nameof(MAX_ATRASO), ref fMAX_ATRASO, value); }
        }
        short fPRO_ATRASO;
        public short PRO_ATRASO
        {
            get { return fPRO_ATRASO; }
            set { SetPropertyValue<short>(nameof(PRO_ATRASO), ref fPRO_ATRASO, value); }
        }
        string fADM_TARJETA;
        [Size(1)]
        [ColumnDbDefaultValue("'B'")]
        public string ADM_TARJETA
        {
            get { return fADM_TARJETA; }
            set { SetPropertyValue<string>(nameof(ADM_TARJETA), ref fADM_TARJETA, value); }
        }
        decimal fSAL_ADMINISTRADORA;
        public decimal SAL_ADMINISTRADORA
        {
            get { return fSAL_ADMINISTRADORA; }
            set { SetPropertyValue<decimal>(nameof(SAL_ADMINISTRADORA), ref fSAL_ADMINISTRADORA, value); }
        }
        short fDIA_ATRASO;
        public short DIA_ATRASO
        {
            get { return fDIA_ATRASO; }
            set { SetPropertyValue<short>(nameof(DIA_ATRASO), ref fDIA_ATRASO, value); }
        }
    }

}
