//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace IntegracionITGF.ITGFDataModel
{

    public partial class INT_PR_SOL_CARGOS : XPLiteObject
    {
        int? fNRO_SOLICITUD;
        public int? NRO_SOLICITUD
        {
            get { return fNRO_SOLICITUD; }
            set { SetPropertyValue<int?>(nameof(NRO_SOLICITUD), ref fNRO_SOLICITUD, value); }
        }
        short? fCOD_TRANSACCION;
        public short? COD_TRANSACCION
        {
            get { return fCOD_TRANSACCION; }
            set { SetPropertyValue<short?>(nameof(COD_TRANSACCION), ref fCOD_TRANSACCION, value); }
        }
        DateTime fFEC_TASA;
        public DateTime FEC_TASA
        {
            get { return fFEC_TASA; }
            set { SetPropertyValue<DateTime>(nameof(FEC_TASA), ref fFEC_TASA, value); }
        }
        decimal? fVAL_TASA;
        [ColumnDbDefaultValue("0")]
        public decimal? VAL_TASA
        {
            get { return fVAL_TASA; }
            set { SetPropertyValue<decimal?>(nameof(VAL_TASA), ref fVAL_TASA, value); }
        }
        decimal? fMONTO;
        [ColumnDbDefaultValue("0")]
        public decimal? MONTO
        {
            get { return fMONTO; }
            set { SetPropertyValue<decimal?>(nameof(MONTO), ref fMONTO, value); }
        }
        byte? fCOD_TASA;
        public byte? COD_TASA
        {
            get { return fCOD_TASA; }
            set { SetPropertyValue<byte?>(nameof(COD_TASA), ref fCOD_TASA, value); }
        }
        short? fCOD_ENT_SEGURO;
        public short? COD_ENT_SEGURO
        {
            get { return fCOD_ENT_SEGURO; }
            set { SetPropertyValue<short?>(nameof(COD_ENT_SEGURO), ref fCOD_ENT_SEGURO, value); }
        }
        string fCOD_MONEDA;
        [Size(3)]
        public string COD_MONEDA
        {
            get { return fCOD_MONEDA; }
            set { SetPropertyValue<string>(nameof(COD_MONEDA), ref fCOD_MONEDA, value); }
        }
        decimal? fMTO_MON_PRESTAMO;
        [ColumnDbDefaultValue("0")]
        public decimal? MTO_MON_PRESTAMO
        {
            get { return fMTO_MON_PRESTAMO; }
            set { SetPropertyValue<decimal?>(nameof(MTO_MON_PRESTAMO), ref fMTO_MON_PRESTAMO, value); }
        }
        string fUSU_INSERCION;
        [Size(10)]
        [ColumnDbDefaultValue("SUBSTR(USER,1,10) ")]
        public string USU_INSERCION
        {
            get { return fUSU_INSERCION; }
            set { SetPropertyValue<string>(nameof(USU_INSERCION), ref fUSU_INSERCION, value); }
        }
        DateTime fFEC_INSERCION;
        [ColumnDbDefaultValue("SYSDATE ")]
        public DateTime FEC_INSERCION
        {
            get { return fFEC_INSERCION; }
            set { SetPropertyValue<DateTime>(nameof(FEC_INSERCION), ref fFEC_INSERCION, value); }
        }
        string fUSU_MODIFICACION;
        [Size(10)]
        [ColumnDbDefaultValue("SUBSTR(USER,1,10) ")]
        public string USU_MODIFICACION
        {
            get { return fUSU_MODIFICACION; }
            set { SetPropertyValue<string>(nameof(USU_MODIFICACION), ref fUSU_MODIFICACION, value); }
        }
        DateTime fFEC_MODIFICACION;
        [ColumnDbDefaultValue("SYSDATE ")]
        public DateTime FEC_MODIFICACION
        {
            get { return fFEC_MODIFICACION; }
            set { SetPropertyValue<DateTime>(nameof(FEC_MODIFICACION), ref fFEC_MODIFICACION, value); }
        }
        string fOID;
        [Key]
        [Size(36)]
        public string OID
        {
            get { return fOID; }
            set { SetPropertyValue<string>(nameof(OID), ref fOID, value); }
        }
        string fID_SOLICITUD;
        [Size(36)]
        public string ID_SOLICITUD
        {
            get { return fID_SOLICITUD; }
            set { SetPropertyValue<string>(nameof(ID_SOLICITUD), ref fID_SOLICITUD, value); }
        }
        string fID_CARGO;
        [Size(36)]
        public string ID_CARGO
        {
            get { return fID_CARGO; }
            set { SetPropertyValue<string>(nameof(ID_CARGO), ref fID_CARGO,value ); }
        }
        string fPROCESADO;
        [Size(1)]
        public string PROCESADO
        {
            get { return fPROCESADO; }
            set { SetPropertyValue<string>(nameof(PROCESADO), ref fPROCESADO, value); }
        }
    }

}
