//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace IntegracionITGF.ITGFDataModel
{

    public partial class INT_PR_GARANTIAS : XPLiteObject
    {
        int? fNRO_GARANTIA;
        public int? NRO_GARANTIA
        {
            get { return fNRO_GARANTIA; }
            set { SetPropertyValue<int?>(nameof(NRO_GARANTIA), ref fNRO_GARANTIA, value); }
        }
        byte? fCOD_GARANTIA;
        public byte? COD_GARANTIA
        {
            get { return fCOD_GARANTIA; }
            set { SetPropertyValue<byte?>(nameof(COD_GARANTIA), ref fCOD_GARANTIA, value); }
        }
        string fCOD_MONEDA;
        [Size(3)]
        public string COD_MONEDA
        {
            get { return fCOD_MONEDA; }
            set { SetPropertyValue<string>(nameof(COD_MONEDA), ref fCOD_MONEDA, value); }
        }
        decimal? fVALOR;
        public decimal? VALOR
        {
            get { return fVALOR; }
            set { SetPropertyValue<decimal?>(nameof(VALOR), ref fVALOR, value); }
        }
        decimal? fVAL_TASACION;
        public decimal? VAL_TASACION
        {
            get { return fVAL_TASACION; }
            set { SetPropertyValue<decimal?>(nameof(VAL_TASACION), ref fVAL_TASACION, value); }
        }
        DateTime fFEC_ULT_TASACION;
        public DateTime FEC_ULT_TASACION
        {
            get { return fFEC_ULT_TASACION; }
            set { SetPropertyValue<DateTime>(nameof(FEC_ULT_TASACION), ref fFEC_ULT_TASACION, value); }
        }
        DateTime fFEC_INICIO;
        public DateTime FEC_INICIO
        {
            get { return fFEC_INICIO; }
            set { SetPropertyValue<DateTime>(nameof(FEC_INICIO), ref fFEC_INICIO, value); }
        }
        DateTime fFEC_VENCIMIENTO;
        public DateTime FEC_VENCIMIENTO
        {
            get { return fFEC_VENCIMIENTO; }
            set { SetPropertyValue<DateTime>(nameof(FEC_VENCIMIENTO), ref fFEC_VENCIMIENTO, value); }
        }
        short? fCOD_ENT_ESCRIBANIA;
        public short? COD_ENT_ESCRIBANIA
        {
            get { return fCOD_ENT_ESCRIBANIA; }
            set { SetPropertyValue<short?>(nameof(COD_ENT_ESCRIBANIA), ref fCOD_ENT_ESCRIBANIA, value); }
        }
        short? fCOD_ENT_SEGURO;
        public short? COD_ENT_SEGURO
        {
            get { return fCOD_ENT_SEGURO; }
            set { SetPropertyValue<short?>(nameof(COD_ENT_SEGURO), ref fCOD_ENT_SEGURO, value); }
        }
        string fTIPO;
        [Size(1)]
        [ColumnDbDefaultValue("'A'")]
        public string TIPO
        {
            get { return fTIPO; }
            set { SetPropertyValue<string>(nameof(TIPO), ref fTIPO, value); }
        }
        string fESTADO;
        [Size(1)]
        public string ESTADO
        {
            get { return fESTADO; }
            set { SetPropertyValue<string>(nameof(ESTADO), ref fESTADO, value); }
        }
        string fCOD_PERSONA;
        [Size(10)]
        public string COD_PERSONA
        {
            get { return fCOD_PERSONA; }
            set { SetPropertyValue<string>(nameof(COD_PERSONA), ref fCOD_PERSONA, value); }
        }
        string fOBSERVACION;
        [Size(1000)]
        public string OBSERVACION
        {
            get { return fOBSERVACION; }
            set { SetPropertyValue<string>(nameof(OBSERVACION), ref fOBSERVACION, value); }
        }
        string fUSU_INSERCION;
        [Size(10)]
        [ColumnDbDefaultValue("SUBSTR(USER,1,10) ")]
        public string USU_INSERCION
        {
            get { return fUSU_INSERCION; }
            set { SetPropertyValue<string>(nameof(USU_INSERCION), ref fUSU_INSERCION, value); }
        }
        DateTime fFEC_INSERCION;
        [ColumnDbDefaultValue("SYSDATE ")]
        public DateTime FEC_INSERCION
        {
            get { return fFEC_INSERCION; }
            set { SetPropertyValue<DateTime>(nameof(FEC_INSERCION), ref fFEC_INSERCION, value); }
        }
        string fUSU_MODIFICACION;
        [Size(10)]
        [ColumnDbDefaultValue("SUBSTR(USER,1,10) ")]
        public string USU_MODIFICACION
        {
            get { return fUSU_MODIFICACION; }
            set { SetPropertyValue<string>(nameof(USU_MODIFICACION), ref fUSU_MODIFICACION, value); }
        }
        DateTime fFEC_MODIFICACION;
        [ColumnDbDefaultValue("SYSDATE ")]
        public DateTime FEC_MODIFICACION
        {
            get { return fFEC_MODIFICACION; }
            set { SetPropertyValue<DateTime>(nameof(FEC_MODIFICACION), ref fFEC_MODIFICACION, value); }
        }
        string fCOD_MON_TASACION;
        [Size(3)]
        public string COD_MON_TASACION
        {
            get { return fCOD_MON_TASACION; }
            set { SetPropertyValue<string>(nameof(COD_MON_TASACION), ref fCOD_MON_TASACION, value); }
        }
        decimal? fMTO_APLICADO;
        public decimal? MTO_APLICADO
        {
            get { return fMTO_APLICADO; }
            set { SetPropertyValue<decimal?>(nameof(MTO_APLICADO), ref fMTO_APLICADO, value); }
        }
        string fEST_TESORERIA;
        [Size(1)]
        [ColumnDbDefaultValue("'F'")]
        public string EST_TESORERIA
        {
            get { return fEST_TESORERIA; }
            set { SetPropertyValue<string>(nameof(EST_TESORERIA), ref fEST_TESORERIA, value); }
        }
        string fEST_VERIFICACION;
        [Size(1)]
        [ColumnDbDefaultValue("'N'")]
        public string EST_VERIFICACION
        {
            get { return fEST_VERIFICACION; }
            set { SetPropertyValue<string>(nameof(EST_VERIFICACION), ref fEST_VERIFICACION, value); }
        }
        DateTime fFEC_ENT_TESORERIA;
        public DateTime FEC_ENT_TESORERIA
        {
            get { return fFEC_ENT_TESORERIA; }
            set { SetPropertyValue<DateTime>(nameof(FEC_ENT_TESORERIA), ref fFEC_ENT_TESORERIA, value); }
        }
        DateTime fFEC_SAL_TESORERIA;
        public DateTime FEC_SAL_TESORERIA
        {
            get { return fFEC_SAL_TESORERIA; }
            set { SetPropertyValue<DateTime>(nameof(FEC_SAL_TESORERIA), ref fFEC_SAL_TESORERIA, value); }
        }
        string fCOD_USU_ENTREGADO;
        [Size(10)]
        public string COD_USU_ENTREGADO
        {
            get { return fCOD_USU_ENTREGADO; }
            set { SetPropertyValue<string>(nameof(COD_USU_ENTREGADO), ref fCOD_USU_ENTREGADO, value); }
        }
        byte? fCOD_CAU_SALIDA;
        public byte? COD_CAU_SALIDA
        {
            get { return fCOD_CAU_SALIDA; }
            set { SetPropertyValue<byte?>(nameof(COD_CAU_SALIDA), ref fCOD_CAU_SALIDA, value); }
        }
        decimal? fMTO_APL_VALOR;
        public decimal? MTO_APL_VALOR
        {
            get { return fMTO_APL_VALOR; }
            set { SetPropertyValue<decimal?>(nameof(MTO_APL_VALOR), ref fMTO_APL_VALOR, value); }
        }
        string fIND_UTI_TERCERO;
        [Size(1)]
        [ColumnDbDefaultValue("'N'")]
        public string IND_UTI_TERCERO
        {
            get { return fIND_UTI_TERCERO; }
            set { SetPropertyValue<string>(nameof(IND_UTI_TERCERO), ref fIND_UTI_TERCERO, value); }
        }
        string fSITUACION;
        [Size(1)]
        public string SITUACION
        {
            get { return fSITUACION; }
            set { SetPropertyValue<string>(nameof(SITUACION), ref fSITUACION, value); }
        }
        byte? fCOD_OFICINA;
        public byte? COD_OFICINA
        {
            get { return fCOD_OFICINA; }
            set { SetPropertyValue<byte?>(nameof(COD_OFICINA), ref fCOD_OFICINA, value); }
        }
        int? fNRO_ESCRITURA;
        public int? NRO_ESCRITURA
        {
            get { return fNRO_ESCRITURA; }
            set { SetPropertyValue<int?>(nameof(NRO_ESCRITURA), ref fNRO_ESCRITURA, value); }
        }
        DateTime fFEC_ULT_UTILIZACION;
        public DateTime FEC_ULT_UTILIZACION
        {
            get { return fFEC_ULT_UTILIZACION; }
            set { SetPropertyValue<DateTime>(nameof(FEC_ULT_UTILIZACION), ref fFEC_ULT_UTILIZACION, value); }
        }
        string fOBSERVACION_HIS;
        [Size(4000)]
        public string OBSERVACION_HIS
        {
            get { return fOBSERVACION_HIS; }
            set { SetPropertyValue<string>(nameof(OBSERVACION_HIS), ref fOBSERVACION_HIS, value); }
        }
        string fNRO_REFERENCIA;
        [Size(20)]
        public string NRO_REFERENCIA
        {
            get { return fNRO_REFERENCIA; }
            set { SetPropertyValue<string>(nameof(NRO_REFERENCIA), ref fNRO_REFERENCIA, value); }
        }
        string fPERFECCIONADA;
        [Size(1)]
        [ColumnDbDefaultValue("'N' ")]
        public string PERFECCIONADA
        {
            get { return fPERFECCIONADA; }
            set { SetPropertyValue<string>(nameof(PERFECCIONADA), ref fPERFECCIONADA, value); }
        }
        string fRANGO;
        [Size(1)]
        [ColumnDbDefaultValue("'1' ")]
        public string RANGO
        {
            get { return fRANGO; }
            set { SetPropertyValue<string>(nameof(RANGO), ref fRANGO, value); }
        }
        DateTime fFEC_CONFIRMACION;
        public DateTime FEC_CONFIRMACION
        {
            get { return fFEC_CONFIRMACION; }
            set { SetPropertyValue<DateTime>(nameof(FEC_CONFIRMACION), ref fFEC_CONFIRMACION, value); }
        }
        string fID_PERSONA;
        [Size(36)]
        public string ID_PERSONA
        {
            get { return fID_PERSONA; }
            set { SetPropertyValue<string>(nameof(ID_PERSONA), ref fID_PERSONA, value); }
        }
        string fOID;
        [Key]
        [Size(36)]
        public string OID
        {
            get { return fOID; }
            set { SetPropertyValue<string>(nameof(OID), ref fOID, value); }
        }
        string fNRO_FINCA;
        [Size(20)]
        public string NRO_FINCA
        {
            get { return fNRO_FINCA; }
            set { SetPropertyValue<string>(nameof(NRO_FINCA), ref fNRO_FINCA, value); }
        }
        int? fCOD_DISTRITO;
        public int? COD_DISTRITO
        {
            get { return fCOD_DISTRITO; }
            set { SetPropertyValue<int?>(nameof(COD_DISTRITO), ref fCOD_DISTRITO, value); }
        }
        string fCTA_CATASTRAL;
        [Size(20)]
        public string CTA_CATASTRAL
        {
            get { return fCTA_CATASTRAL; }
            set { SetPropertyValue<string>(nameof(CTA_CATASTRAL), ref fCTA_CATASTRAL, value); }
        }
        string fDIRECCION;
        [Size(80)]
        public string DIRECCION
        {
            get { return fDIRECCION; }
            set { SetPropertyValue<string>(nameof(DIRECCION), ref fDIRECCION, value); }
        }
        decimal? fVAL_TERRENO;
        public decimal? VAL_TERRENO
        {
            get { return fVAL_TERRENO; }
            set { SetPropertyValue<decimal?>(nameof(VAL_TERRENO), ref fVAL_TERRENO, value); }
        }

        decimal? fVAL_EDILICIO;
        public decimal? VAL_EDILICIO
        {
            get { return fVAL_EDILICIO; }
            set { SetPropertyValue<decimal?>(nameof(VAL_EDILICIO), ref fVAL_EDILICIO, value); }
        }

        string fNRO_POLIZA;
        [Size(20)]
        public string NRO_POLIZA
        {
            get { return fNRO_POLIZA; }
            set { SetPropertyValue<string>(nameof(NRO_POLIZA), ref fNRO_POLIZA, value); }
        }
        DateTime fFEC_VTO_SEGURO;
        public DateTime FEC_VTO_SEGURO
        {
            get { return fFEC_VTO_SEGURO; }
            set { SetPropertyValue<DateTime>(nameof(FEC_VTO_SEGURO), ref fFEC_VTO_SEGURO, value); }
        }
        string fSERIE;
        [Size(5)]
        public string SERIE
        {
            get { return fSERIE; }
            set { SetPropertyValue<string>(nameof(SERIE), ref fSERIE, value); }
        }
        int? fNRO_INSCRIPCION;
        public int? NRO_INSCRIPCION
        {
            get { return fNRO_INSCRIPCION; }
            set { SetPropertyValue<int?>(nameof(NRO_INSCRIPCION), ref fNRO_INSCRIPCION, value); }
        }
        short? fNRO_FOLIO;
        public short? NRO_FOLIO
        {
            get { return fNRO_FOLIO; }
            set { SetPropertyValue<short?>(nameof(NRO_FOLIO), ref fNRO_FOLIO, value); }
        }
        DateTime fFEC_INSCRIPCION;
        public DateTime FEC_INSCRIPCION
        {
            get { return fFEC_INSCRIPCION; }
            set { SetPropertyValue<DateTime>(nameof(FEC_INSCRIPCION), ref fFEC_INSCRIPCION, value); }
        }
        decimal? fVAL_VTA_RAPIDA;
        public decimal? VAL_VTA_RAPIDA
        {
            get { return fVAL_VTA_RAPIDA; }
            set { SetPropertyValue<decimal?>(nameof(VAL_VTA_RAPIDA), ref fVAL_VTA_RAPIDA, value); }
        }
        decimal? fVAL_SEGURO;
        public decimal? VAL_SEGURO
        {
            get { return fVAL_SEGURO; }
            set { SetPropertyValue<decimal?>(nameof(VAL_SEGURO), ref fVAL_SEGURO, value); }
        }
        short? fCOD_ENT_TASADOR;
        public short? COD_ENT_TASADOR
        {
            get { return fCOD_ENT_TASADOR; }
            set { SetPropertyValue<short?>(nameof(COD_ENT_TASADOR), ref fCOD_ENT_TASADOR, value); }
        }
        DateTime fFEC_INI_SEGURO;
        public DateTime FEC_INI_SEGURO
        {
            get { return fFEC_INI_SEGURO; }
            set { SetPropertyValue<DateTime>(nameof(FEC_INI_SEGURO), ref fFEC_INI_SEGURO, value); }
        }
        byte? fCOD_ENT_FIDUCIARIA;
        public byte? COD_ENT_FIDUCIARIA
        {
            get { return fCOD_ENT_FIDUCIARIA; }
            set { SetPropertyValue<byte?>(nameof(COD_ENT_FIDUCIARIA), ref fCOD_ENT_FIDUCIARIA, value); }
        }
        string fID_GARANTIA;
        [Size(36)]
        public string ID_GARANTIA
        {
            get { return fID_GARANTIA; }
            set { SetPropertyValue<string>(nameof(ID_GARANTIA), ref fID_GARANTIA, value); }
        }
        string fPROCESADO;
        [Size(1)]
        [ColumnDbDefaultValue("'N' ")]
        public string PROCESADO
        {
            get { return fPROCESADO; }
            set { SetPropertyValue<string>(nameof(PROCESADO), ref fPROCESADO, value); }
        }

        DateTime fFEC_ESCRITURA;
        public DateTime FEC_ESCRITURA
        {
            get { return fFEC_ESCRITURA; }
            set { SetPropertyValue<DateTime>(nameof(FEC_ESCRITURA), ref fFEC_ESCRITURA, value); }
        }
    }

}
