//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace IntegracionITGF.ITGFDataModel
{

    public partial class INT_BA_VINCULOS : XPLiteObject
    {
        string fCOD_PERSONA;
        [Size(10)]
        public string COD_PERSONA
        {
            get { return fCOD_PERSONA; }
            set { SetPropertyValue<string>(nameof(COD_PERSONA), ref fCOD_PERSONA, value); }
        }

        string fCOD_PER_VINCULO;
        [Size(10)]
        public string COD_PER_VINCULO
        {
            get { return fCOD_PER_VINCULO; }
            set { SetPropertyValue<string>(nameof(COD_PER_VINCULO), ref fCOD_PER_VINCULO, value); }
        }

        string fTIPO;
        [Size(2)]
        public string TIPO
        {
            get { return fTIPO; }
            set { SetPropertyValue<string>(nameof(TIPO), ref fTIPO, value); }
        }

        DateTime fFEC_VENCIMIENTO;
        public DateTime FEC_VENCIMIENTO
        {
            get { return fFEC_VENCIMIENTO; }
            set { SetPropertyValue<DateTime>(nameof(FEC_VENCIMIENTO), ref fFEC_VENCIMIENTO, value); }
        }

        string fCOD_PERFIL;
        [Size(20)]
        public string COD_PERFIL
        {
            get { return fCOD_PERFIL; }
            set { SetPropertyValue<string>(nameof(COD_PERFIL), ref fCOD_PERFIL, value); }
        }

        string fACTIVO;
        [Size(1)]
        public string ACTIVO
        {
            get { return fACTIVO; }
            set { SetPropertyValue<string>(nameof(ACTIVO), ref fACTIVO, value); }
        }

        string fPER_ADMINISTRADOR;
        [Size(1)]
        public string PER_ADMINISTRADOR
        {
            get { return fPER_ADMINISTRADOR; }
            set { SetPropertyValue<string>(nameof(PER_ADMINISTRADOR), ref fPER_ADMINISTRADOR, value); }
        }
        string fESTADO;
        [Size(1)]
        public string ESTADO
        {
            get { return fESTADO; }
            set { SetPropertyValue<string>(nameof(ESTADO), ref fESTADO, value); }
        }

        string fNRO_DOC_VINCULO;
        [Size(20)]
        public string NRO_DOC_VINCULO
        {
            get { return fNRO_DOC_VINCULO; }
            set { SetPropertyValue<string>(nameof(NRO_DOC_VINCULO), ref fNRO_DOC_VINCULO, value); }
        }

        string fNRO_DOCUMENTO;
        [Size(20)]
        public string NRO_DOCUMENTO
        {
            get { return fNRO_DOCUMENTO; }
            set { SetPropertyValue<string>(nameof(NRO_DOCUMENTO), ref fNRO_DOCUMENTO, value); }
        }

        string fID_VINCULO;
        [Size(36)]
        public string ID_VINCULO
        {
            get { return fID_VINCULO; }
            set { SetPropertyValue<string>(nameof(ID_VINCULO), ref fID_VINCULO, value); }
        }

        string fOID;
        [Key]
        [Size(36)]
        public string OID
        {
            get { return fOID; }
            set { SetPropertyValue<string>(nameof(OID), ref fOID, value); }
        }
    
        string fPROCESADO;
        [Size(1)]
        [ColumnDbDefaultValue("'N' ")]
        public string PROCESADO
        {
            get { return fPROCESADO; }
            set { SetPropertyValue<string>(nameof(PROCESADO), ref fPROCESADO, value); }
        }

        string fID_PER_VINCULO;
        [Size(36)]
        public string ID_PER_VINCULO
        {
            get { return fID_PER_VINCULO; }
            set { SetPropertyValue<string>(nameof(ID_PER_VINCULO), ref fID_PER_VINCULO, value); }
        }
    }

}
