//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace IntegracionITGF.ITGFDataModel
{

    public partial class INT_PR_SOL_GARANTIAS : XPLiteObject
    {
        int fNRO_SOLICITUD;
        public int NRO_SOLICITUD
        {
            get { return fNRO_SOLICITUD; }
            set { SetPropertyValue<int>(nameof(NRO_SOLICITUD), ref fNRO_SOLICITUD, value); }
        }
        int fNRO_GARANTIA;
        public int NRO_GARANTIA
        {
            get { return fNRO_GARANTIA; }
            set { SetPropertyValue<int>(nameof(NRO_GARANTIA), ref fNRO_GARANTIA, value); }
        }
        byte fCOD_GARANTIA;
        public byte COD_GARANTIA
        {
            get { return fCOD_GARANTIA; }
            set { SetPropertyValue<byte>(nameof(COD_GARANTIA), ref fCOD_GARANTIA, value); }
        }
        decimal fMTO_APLICADO;
        [ColumnDbDefaultValue("0 ")]
        public decimal MTO_APLICADO
        {
            get { return fMTO_APLICADO; }
            set { SetPropertyValue<decimal>(nameof(MTO_APLICADO), ref fMTO_APLICADO, value); }
        }
        string fUSU_INSERCION;
        [Size(10)]
        [ColumnDbDefaultValue("SUBSTR(USER,1,10) ")]
        public string USU_INSERCION
        {
            get { return fUSU_INSERCION; }
            set { SetPropertyValue<string>(nameof(USU_INSERCION), ref fUSU_INSERCION, value); }
        }
        DateTime fFEC_INSERCION;
        [ColumnDbDefaultValue("SYSDATE ")]
        public DateTime FEC_INSERCION
        {
            get { return fFEC_INSERCION; }
            set { SetPropertyValue<DateTime>(nameof(FEC_INSERCION), ref fFEC_INSERCION, value); }
        }
        string fUSU_MODIFICACION;
        [Size(10)]
        [ColumnDbDefaultValue("SUBSTR(USER,1,10) ")]
        public string USU_MODIFICACION
        {
            get { return fUSU_MODIFICACION; }
            set { SetPropertyValue<string>(nameof(USU_MODIFICACION), ref fUSU_MODIFICACION, value); }
        }
        DateTime fFEC_MODIFICACION;
        [ColumnDbDefaultValue("SYSDATE ")]
        public DateTime FEC_MODIFICACION
        {
            get { return fFEC_MODIFICACION; }
            set { SetPropertyValue<DateTime>(nameof(FEC_MODIFICACION), ref fFEC_MODIFICACION, value); }
        }
        decimal fPORCENTAJE;
        public decimal PORCENTAJE
        {
            get { return fPORCENTAJE; }
            set { SetPropertyValue<decimal>(nameof(PORCENTAJE), ref fPORCENTAJE, value); }
        }
        string fOID;
        [Key]
        [Size(36)]
        public string OID
        {
            get { return fOID; }
            set { SetPropertyValue<string>(nameof(OID), ref fOID, value); }
        }
        string fID_SOLICITUD;
        [Size(36)]
        public string ID_SOLICITUD
        {
            get { return fID_SOLICITUD; }
            set { SetPropertyValue<string>(nameof(ID_SOLICITUD), ref fID_SOLICITUD, value); }
        }
        string fID_GARANTIA;
        [Size(36)]
        public string ID_GARANTIA
        {
            get { return fID_GARANTIA; }
            set { SetPropertyValue<string>(nameof(ID_GARANTIA), ref fID_GARANTIA, value); }
        }
        string fPROCESADO;
        [Size(1)]
        public string PROCESADO
        {
            get { return fPROCESADO; }
            set { SetPropertyValue<string>(nameof(PROCESADO), ref fPROCESADO, value); }
        }

        string fID_PERSONA;
        [Size(36)]
        public string ID_PERSONA
        {
            get { return fID_PERSONA; }
            set { SetPropertyValue<string>(nameof(ID_PERSONA), ref fID_PERSONA, value); }
        }
    }

}
