//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace IntegracionITGF.ITGFDataModel
{

    public partial class INT_CR_PER_ING_EGRESOS : XPLiteObject
    {
        string fID_PERSONA;
        [Size(36)]
        public string ID_PERSONA
        {
            get { return fID_PERSONA; }
            set { SetPropertyValue<string>(nameof(ID_PERSONA), ref fID_PERSONA, value); }
        }
        string fOID;
        [Key]
        [Size(36)]
        public string OID
        {
            get { return fOID; }
            set { SetPropertyValue<string>(nameof(OID), ref fOID, value); }
        }
        string fID_INGRESO;
        [Size(36)]
        public string ID_INGRESO
        {
            get { return fID_INGRESO; }
            set { SetPropertyValue<string>(nameof(ID_INGRESO), ref fID_INGRESO, value); }
        }
        string fCOD_PERSONA;
        [Size(10)]
        public string COD_PERSONA
        {
            get { return fCOD_PERSONA; }
            set { SetPropertyValue<string>(nameof(COD_PERSONA), ref fCOD_PERSONA, value); }
        }
        byte fCOD_CONCEPTO;
        public byte COD_CONCEPTO
        {
            get { return fCOD_CONCEPTO; }
            set { SetPropertyValue<byte>(nameof(COD_CONCEPTO), ref fCOD_CONCEPTO, value); }
        }
        string fING_EGRESO;
        [Size(1)]
        public string ING_EGRESO
        {
            get { return fING_EGRESO; }
            set { SetPropertyValue<string>(nameof(ING_EGRESO), ref fING_EGRESO, value); }
        }
        decimal fIMPORTE;
        [ColumnDbDefaultValue("0 ")]
        public decimal IMPORTE
        {
            get { return fIMPORTE; }
            set { SetPropertyValue<decimal>(nameof(IMPORTE), ref fIMPORTE, value); }
        }
        string fUSU_INSERCION;
        [Size(10)]
        [ColumnDbDefaultValue("SUBSTR(USER,1,10) ")]
        public string USU_INSERCION
        {
            get { return fUSU_INSERCION; }
            set { SetPropertyValue<string>(nameof(USU_INSERCION), ref fUSU_INSERCION, value); }
        }
        DateTime fFEC_INSERCION;
        [ColumnDbDefaultValue("SYSDATE ")]
        public DateTime FEC_INSERCION
        {
            get { return fFEC_INSERCION; }
            set { SetPropertyValue<DateTime>(nameof(FEC_INSERCION), ref fFEC_INSERCION, value); }
        }
        string fUSU_MODIFICACION;
        [Size(10)]
        [ColumnDbDefaultValue("SUBSTR(USER,1,10) ")]
        public string USU_MODIFICACION
        {
            get { return fUSU_MODIFICACION; }
            set { SetPropertyValue<string>(nameof(USU_MODIFICACION), ref fUSU_MODIFICACION, value); }
        }
        DateTime fFEC_MODIFICACION;
        [ColumnDbDefaultValue("SYSDATE ")]
        public DateTime FEC_MODIFICACION
        {
            get { return fFEC_MODIFICACION; }
            set { SetPropertyValue<DateTime>(nameof(FEC_MODIFICACION), ref fFEC_MODIFICACION, value); }
        }
        DateTime fFEC_INFORMACION;
        [ColumnDbDefaultValue("SYSDATE")]
        public DateTime FEC_INFORMACION
        {
            get { return fFEC_INFORMACION; }
            set { SetPropertyValue<DateTime>(nameof(FEC_INFORMACION), ref fFEC_INFORMACION, value); }
        }
        decimal fMTO_SAL_PENDIENTE;
        public decimal MTO_SAL_PENDIENTE
        {
            get { return fMTO_SAL_PENDIENTE; }
            set { SetPropertyValue<decimal>(nameof(MTO_SAL_PENDIENTE), ref fMTO_SAL_PENDIENTE, value); }
        }
        decimal fMTO_EXONERADO;
        public decimal MTO_EXONERADO
        {
            get { return fMTO_EXONERADO; }
            set { SetPropertyValue<decimal>(nameof(MTO_EXONERADO), ref fMTO_EXONERADO, value); }
        }
        string fPROCESADO;
        [Size(36)]
        public string PROCESADO
        {
            get { return fPROCESADO; }
            set { SetPropertyValue<string>(nameof(PROCESADO), ref fPROCESADO, value); }
        }
    }

}
