//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace IntegracionITGF.ITGFDataModel
{

    public partial class INT_BA_TELEFONOS : XPLiteObject
    {
        string fCOD_PERSONA;
        [Size(10)]
        public string COD_PERSONA
        {
            get { return fCOD_PERSONA; }
            set { SetPropertyValue<string>(nameof(COD_PERSONA), ref fCOD_PERSONA, value); }
        }
        string fTIPO;
        [Size(1)]
        public string TIPO
        {
            get { return fTIPO; }
            set { SetPropertyValue<string>(nameof(TIPO), ref fTIPO, value); }
        }
        string fTIP_LINEA;
        [Size(1)]
        [ColumnDbDefaultValue("'B' ")]
        public string TIP_LINEA
        {
            get { return fTIP_LINEA; }
            set { SetPropertyValue<string>(nameof(TIP_LINEA), ref fTIP_LINEA, value); }
        }
        string fTELEFONO;
        [Size(10)]
        public string TELEFONO
        {
            get { return fTELEFONO; }
            set { SetPropertyValue<string>(nameof(TELEFONO), ref fTELEFONO, value); }
        }
        string fPRINCIPAL;
        [Size(1)]
        [ColumnDbDefaultValue("'N' ")]
        public string PRINCIPAL
        {
            get { return fPRINCIPAL; }
            set { SetPropertyValue<string>(nameof(PRINCIPAL), ref fPRINCIPAL, value); }
        }
        string fAREA;
        [Size(10)]
        public string AREA
        {
            get { return fAREA; }
            set { SetPropertyValue<string>(nameof(AREA), ref fAREA, value); }
        }
        string fINTERNO;
        [Size(5)]
        public string INTERNO
        {
            get { return fINTERNO; }
            set { SetPropertyValue<string>(nameof(INTERNO), ref fINTERNO, value); }
        }
        string fOBSERVACION;
        [Size(1000)]
        public string OBSERVACION
        {
            get { return fOBSERVACION; }
            set { SetPropertyValue<string>(nameof(OBSERVACION), ref fOBSERVACION, value); }
        }
        string fUSU_INSERCION;
        [Size(10)]
        [ColumnDbDefaultValue("SUBSTR(USER,1,10)")]
        public string USU_INSERCION
        {
            get { return fUSU_INSERCION; }
            set { SetPropertyValue<string>(nameof(USU_INSERCION), ref fUSU_INSERCION, value); }
        }
        DateTime fFEC_INSERCION;
        [ColumnDbDefaultValue("SYSDATE")]
        public DateTime FEC_INSERCION
        {
            get { return fFEC_INSERCION; }
            set { SetPropertyValue<DateTime>(nameof(FEC_INSERCION), ref fFEC_INSERCION, value); }
        }
        string fUSU_MODIFICACION;
        [Size(10)]
        [ColumnDbDefaultValue("SUBSTR(USER,1,10)")]
        public string USU_MODIFICACION
        {
            get { return fUSU_MODIFICACION; }
            set { SetPropertyValue<string>(nameof(USU_MODIFICACION), ref fUSU_MODIFICACION, value); }
        }
        DateTime fFEC_MODIFICACION;
        [ColumnDbDefaultValue("SYSDATE")]
        public DateTime FEC_MODIFICACION
        {
            get { return fFEC_MODIFICACION; }
            set { SetPropertyValue<DateTime>(nameof(FEC_MODIFICACION), ref fFEC_MODIFICACION, value); }
        }
        byte fCOD_TELEFONO;
        public byte COD_TELEFONO
        {
            get { return fCOD_TELEFONO; }
            set { SetPropertyValue<byte>(nameof(COD_TELEFONO), ref fCOD_TELEFONO, value); }
        }
        string fSMS_HABILITADO;
        [Size(1)]
        public string SMS_HABILITADO
        {
            get { return fSMS_HABILITADO; }
            set { SetPropertyValue<string>(nameof(SMS_HABILITADO), ref fSMS_HABILITADO, value); }
        }
        string fID_PERSONA;
        [Size(36)]
        public string ID_PERSONA
        {
            get { return fID_PERSONA; }
            set { SetPropertyValue<string>(nameof(ID_PERSONA), ref fID_PERSONA, value); }
        }
        string fOID;
        [Key]
        [Size(36)]
        public string OID
        {
            get { return fOID; }
            set { SetPropertyValue<string>(nameof(OID), ref fOID, value); }
        }
        string fID_TELEFONO;
        [Size(36)]
        public string ID_TELEFONO
        {
            get { return fID_TELEFONO; }
            set { SetPropertyValue<string>(nameof(ID_TELEFONO), ref fID_TELEFONO, value); }
        }
        string fPROCESADO;
        [Size(1)]
        [ColumnDbDefaultValue("'N' ")]
        public string PROCESADO
        {
            get { return fPROCESADO; }
            set { SetPropertyValue<string>(nameof(PROCESADO), ref fPROCESADO, value); }
        }
    }

}
