//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace IntegracionITGF.ITGFDataModel
{

    public partial class INT_PR_SOLICITUDES : XPLiteObject
    {
        int fNRO_SOLICITUD;
        public int NRO_SOLICITUD
        {
            get { return fNRO_SOLICITUD; }
            set { SetPropertyValue<int>(nameof(NRO_SOLICITUD), ref fNRO_SOLICITUD, value); }
        }
        string fDESCRIPCION;
        [Size(35)]
        public string DESCRIPCION
        {
            get { return fDESCRIPCION; }
            set { SetPropertyValue<string>(nameof(DESCRIPCION), ref fDESCRIPCION, value); }
        }
        decimal fMONTO;
        [ColumnDbDefaultValue("0 ")]
        public decimal MONTO
        {
            get { return fMONTO; }
            set { SetPropertyValue<decimal>(nameof(MONTO), ref fMONTO, value); }
        }
        string fTIP_INTERES;
        [Size(1)]
        [ColumnDbDefaultValue("'V' ")]
        public string TIP_INTERES
        {
            get { return fTIP_INTERES; }
            set { SetPropertyValue<string>(nameof(TIP_INTERES), ref fTIP_INTERES, value); }
        }
        string fTIP_AMORTIZACION;
        [Size(1)]
        public string TIP_AMORTIZACION
        {
            get { return fTIP_AMORTIZACION; }
            set { SetPropertyValue<string>(nameof(TIP_AMORTIZACION), ref fTIP_AMORTIZACION, value); }
        }
        short fDIA_PLAZO;
        public short DIA_PLAZO
        {
            get { return fDIA_PLAZO; }
            set { SetPropertyValue<short>(nameof(DIA_PLAZO), ref fDIA_PLAZO, value); }
        }
        DateTime fFEC_VENCIMIENTO;
        public DateTime FEC_VENCIMIENTO
        {
            get { return fFEC_VENCIMIENTO; }
            set { SetPropertyValue<DateTime>(nameof(FEC_VENCIMIENTO), ref fFEC_VENCIMIENTO, value); }
        }
        string fAJU_ULT_CUOTA;
        [Size(1)]
        [ColumnDbDefaultValue("'N' ")]
        public string AJU_ULT_CUOTA
        {
            get { return fAJU_ULT_CUOTA; }
            set { SetPropertyValue<string>(nameof(AJU_ULT_CUOTA), ref fAJU_ULT_CUOTA, value); }
        }
        decimal fMTO_INTERES;
        [ColumnDbDefaultValue("0 ")]
        public decimal MTO_INTERES
        {
            get { return fMTO_INTERES; }
            set { SetPropertyValue<decimal>(nameof(MTO_INTERES), ref fMTO_INTERES, value); }
        }
        string fTIP_AJU_FECHA;
        [Size(1)]
        [ColumnDbDefaultValue("'E' ")]
        public string TIP_AJU_FECHA
        {
            get { return fTIP_AJU_FECHA; }
            set { SetPropertyValue<string>(nameof(TIP_AJU_FECHA), ref fTIP_AJU_FECHA, value); }
        }
        short fPER_VTO_CAPITAL;
        public short PER_VTO_CAPITAL
        {
            get { return fPER_VTO_CAPITAL; }
            set { SetPropertyValue<short>(nameof(PER_VTO_CAPITAL), ref fPER_VTO_CAPITAL, value); }
        }
        short fPER_GRACIA;
        public short PER_GRACIA
        {
            get { return fPER_GRACIA; }
            set { SetPropertyValue<short>(nameof(PER_GRACIA), ref fPER_GRACIA, value); }
        }
        string fCOD_PERSONA;
        [Size(10)]
        public string COD_PERSONA
        {
            get { return fCOD_PERSONA; }
            set { SetPropertyValue<string>(nameof(COD_PERSONA), ref fCOD_PERSONA, value); }
        }
        DateTime fFEC_INICIO;
        public DateTime FEC_INICIO
        {
            get { return fFEC_INICIO; }
            set { SetPropertyValue<DateTime>(nameof(FEC_INICIO), ref fFEC_INICIO, value); }
        }
        string fTIP_MONTO;
        [Size(1)]
        public string TIP_MONTO
        {
            get { return fTIP_MONTO; }
            set { SetPropertyValue<string>(nameof(TIP_MONTO), ref fTIP_MONTO, value); }
        }
        string fAJU_GRACIA;
        [Size(1)]
        [ColumnDbDefaultValue("'N' ")]
        public string AJU_GRACIA
        {
            get { return fAJU_GRACIA; }
            set { SetPropertyValue<string>(nameof(AJU_GRACIA), ref fAJU_GRACIA, value); }
        }
        decimal fTOT_PRESTAMO;
        [ColumnDbDefaultValue("0")]
        public decimal TOT_PRESTAMO
        {
            get { return fTOT_PRESTAMO; }
            set { SetPropertyValue<decimal>(nameof(TOT_PRESTAMO), ref fTOT_PRESTAMO, value); }
        }
        string fESTADO;
        [Size(1)]
        [ColumnDbDefaultValue("'C'")]
        public string ESTADO
        {
            get { return fESTADO; }
            set { SetPropertyValue<string>(nameof(ESTADO), ref fESTADO, value); }
        }
        byte fCOD_ORI_FONDO;
        public byte COD_ORI_FONDO
        {
            get { return fCOD_ORI_FONDO; }
            set { SetPropertyValue<byte>(nameof(COD_ORI_FONDO), ref fCOD_ORI_FONDO, value); }
        }
        byte fCOD_MODULO;
        public byte COD_MODULO
        {
            get { return fCOD_MODULO; }
            set { SetPropertyValue<byte>(nameof(COD_MODULO), ref fCOD_MODULO, value); }
        }
        byte fCOD_MODALIDAD;
        public byte COD_MODALIDAD
        {
            get { return fCOD_MODALIDAD; }
            set { SetPropertyValue<byte>(nameof(COD_MODALIDAD), ref fCOD_MODALIDAD, value); }
        }
        string fCOD_MONEDA;
        [Size(3)]
        public string COD_MONEDA
        {
            get { return fCOD_MONEDA; }
            set { SetPropertyValue<string>(nameof(COD_MONEDA), ref fCOD_MONEDA, value); }
        }
        decimal fMTO_CARGO;
        [ColumnDbDefaultValue("0")]
        public decimal MTO_CARGO
        {
            get { return fMTO_CARGO; }
            set { SetPropertyValue<decimal>(nameof(MTO_CARGO), ref fMTO_CARGO, value); }
        }
        byte fCOD_OFICINA;
        public byte COD_OFICINA
        {
            get { return fCOD_OFICINA; }
            set { SetPropertyValue<byte>(nameof(COD_OFICINA), ref fCOD_OFICINA, value); }
        }
        DateTime fFEC_PRI_VENCIMIENTO;
        public DateTime FEC_PRI_VENCIMIENTO
        {
            get { return fFEC_PRI_VENCIMIENTO; }
            set { SetPropertyValue<DateTime>(nameof(FEC_PRI_VENCIMIENTO), ref fFEC_PRI_VENCIMIENTO, value); }
        }
        short fCOD_ENT_SEGURO;
        public short COD_ENT_SEGURO
        {
            get { return fCOD_ENT_SEGURO; }
            set { SetPropertyValue<short>(nameof(COD_ENT_SEGURO), ref fCOD_ENT_SEGURO, value); }
        }
        int fCOD_SEC_CREDITO;
        public int COD_SEC_CREDITO
        {
            get { return fCOD_SEC_CREDITO; }
            set { SetPropertyValue<int>(nameof(COD_SEC_CREDITO), ref fCOD_SEC_CREDITO, value); }
        }
        byte fCOD_DEPARTAMENTO;
        public byte COD_DEPARTAMENTO
        {
            get { return fCOD_DEPARTAMENTO; }
            set { SetPropertyValue<byte>(nameof(COD_DEPARTAMENTO), ref fCOD_DEPARTAMENTO, value); }
        }
        int fNRO_SOL_RENOVADA;
        public int NRO_SOL_RENOVADA
        {
            get { return fNRO_SOL_RENOVADA; }
            set { SetPropertyValue<int>(nameof(NRO_SOL_RENOVADA), ref fNRO_SOL_RENOVADA, value); }
        }
        string fTIP_DOCUMENTO;
        [Size(1)]
        public string TIP_DOCUMENTO
        {
            get { return fTIP_DOCUMENTO; }
            set { SetPropertyValue<string>(nameof(TIP_DOCUMENTO), ref fTIP_DOCUMENTO, value); }
        }
        string fTIPO;
        [Size(1)]
        [ColumnDbDefaultValue("'A'")]
        public string TIPO
        {
            get { return fTIPO; }
            set { SetPropertyValue<string>(nameof(TIPO), ref fTIPO, value); }
        }
        string fEXO_IMPUESTO;
        [Size(1)]
        [ColumnDbDefaultValue("'N'")]
        public string EXO_IMPUESTO
        {
            get { return fEXO_IMPUESTO; }
            set { SetPropertyValue<string>(nameof(EXO_IMPUESTO), ref fEXO_IMPUESTO, value); }
        }
        decimal fTOT_DESEMBOLSAR;
        [ColumnDbDefaultValue("0")]
        public decimal TOT_DESEMBOLSAR
        {
            get { return fTOT_DESEMBOLSAR; }
            set { SetPropertyValue<decimal>(nameof(TOT_DESEMBOLSAR), ref fTOT_DESEMBOLSAR, value); }
        }
        byte fCAN_DESEMBOLSOS;
        public byte CAN_DESEMBOLSOS
        {
            get { return fCAN_DESEMBOLSOS; }
            set { SetPropertyValue<byte>(nameof(CAN_DESEMBOLSOS), ref fCAN_DESEMBOLSOS, value); }
        }
        int fNRO_SOL_ORIGINAL;
        public int NRO_SOL_ORIGINAL
        {
            get { return fNRO_SOL_ORIGINAL; }
            set { SetPropertyValue<int>(nameof(NRO_SOL_ORIGINAL), ref fNRO_SOL_ORIGINAL, value); }
        }
        decimal fSAL_PRESTAMO;
        [ColumnDbDefaultValue("0")]
        public decimal SAL_PRESTAMO
        {
            get { return fSAL_PRESTAMO; }
            set { SetPropertyValue<decimal>(nameof(SAL_PRESTAMO), ref fSAL_PRESTAMO, value); }
        }
        byte fCAN_DES_FALTANTES;
        public byte CAN_DES_FALTANTES
        {
            get { return fCAN_DES_FALTANTES; }
            set { SetPropertyValue<byte>(nameof(CAN_DES_FALTANTES), ref fCAN_DES_FALTANTES, value); }
        }
        short fCOD_ENT_CONCESIONARIA;
        public short COD_ENT_CONCESIONARIA
        {
            get { return fCOD_ENT_CONCESIONARIA; }
            set { SetPropertyValue<short>(nameof(COD_ENT_CONCESIONARIA), ref fCOD_ENT_CONCESIONARIA, value); }
        }
        string fNRO_CTA_DEBITO;
        [Size(15)]
        public string NRO_CTA_DEBITO
        {
            get { return fNRO_CTA_DEBITO; }
            set { SetPropertyValue<string>(nameof(NRO_CTA_DEBITO), ref fNRO_CTA_DEBITO, value); }
        }
        string fDEB_AUTOMATICO;
        [Size(1)]
        [ColumnDbDefaultValue("'N'")]
        public string DEB_AUTOMATICO
        {
            get { return fDEB_AUTOMATICO; }
            set { SetPropertyValue<string>(nameof(DEB_AUTOMATICO), ref fDEB_AUTOMATICO, value); }
        }
        DateTime fFEC_APROBACION;
        public DateTime FEC_APROBACION
        {
            get { return fFEC_APROBACION; }
            set { SetPropertyValue<DateTime>(nameof(FEC_APROBACION), ref fFEC_APROBACION, value); }
        }
        string fCOD_USU_APROBACION;
        [Size(10)]
        public string COD_USU_APROBACION
        {
            get { return fCOD_USU_APROBACION; }
            set { SetPropertyValue<string>(nameof(COD_USU_APROBACION), ref fCOD_USU_APROBACION, value); }
        }
        string fCOD_USU_PROMOTOR;
        [Size(10)]
        public string COD_USU_PROMOTOR
        {
            get { return fCOD_USU_PROMOTOR; }
            set { SetPropertyValue<string>(nameof(COD_USU_PROMOTOR), ref fCOD_USU_PROMOTOR, value); }
        }
        int fNRO_LINEA;
        public int NRO_LINEA
        {
            get { return fNRO_LINEA; }
            set { SetPropertyValue<int>(nameof(NRO_LINEA), ref fNRO_LINEA, value); }
        }
        string fOBSERVACIONES;
        [Size(4000)]
        public string OBSERVACIONES
        {
            get { return fOBSERVACIONES; }
            set { SetPropertyValue<string>(nameof(OBSERVACIONES), ref fOBSERVACIONES, value); }
        }
        string fUSU_INSERCION;
        [Size(10)]
        [ColumnDbDefaultValue("SUBSTR(USER,1,10) ")]
        public string USU_INSERCION
        {
            get { return fUSU_INSERCION; }
            set { SetPropertyValue<string>(nameof(USU_INSERCION), ref fUSU_INSERCION, value); }
        }
        DateTime fFEC_INSERCION;
        [ColumnDbDefaultValue("SYSDATE ")]
        public DateTime FEC_INSERCION
        {
            get { return fFEC_INSERCION; }
            set { SetPropertyValue<DateTime>(nameof(FEC_INSERCION), ref fFEC_INSERCION, value); }
        }
        string fUSU_MODIFICACION;
        [Size(10)]
        [ColumnDbDefaultValue("SUBSTR(USER,1,10) ")]
        public string USU_MODIFICACION
        {
            get { return fUSU_MODIFICACION; }
            set { SetPropertyValue<string>(nameof(USU_MODIFICACION), ref fUSU_MODIFICACION, value); }
        }
        DateTime fFEC_MODIFICACION;
        [ColumnDbDefaultValue("SYSDATE ")]
        public DateTime FEC_MODIFICACION
        {
            get { return fFEC_MODIFICACION; }
            set { SetPropertyValue<DateTime>(nameof(FEC_MODIFICACION), ref fFEC_MODIFICACION, value); }
        }
        byte fCOD_CANAL;
        public byte COD_CANAL
        {
            get { return fCOD_CANAL; }
            set { SetPropertyValue<byte>(nameof(COD_CANAL), ref fCOD_CANAL, value); }
        }
        byte fCOD_CAMPANA;
        public byte COD_CAMPANA
        {
            get { return fCOD_CAMPANA; }
            set { SetPropertyValue<byte>(nameof(COD_CAMPANA), ref fCOD_CAMPANA, value); }
        }
        decimal fMTO_LIN_APLICADO;
        [ColumnDbDefaultValue("0")]
        public decimal MTO_LIN_APLICADO
        {
            get { return fMTO_LIN_APLICADO; }
            set { SetPropertyValue<decimal>(nameof(MTO_LIN_APLICADO), ref fMTO_LIN_APLICADO, value); }
        }
        string fTIP_RENOVACION;
        [Size(1)]
        public string TIP_RENOVACION
        {
            get { return fTIP_RENOVACION; }
            set { SetPropertyValue<string>(nameof(TIP_RENOVACION), ref fTIP_RENOVACION, value); }
        }
        string fTIP_DESTINO;
        [Size(1)]
        public string TIP_DESTINO
        {
            get { return fTIP_DESTINO; }
            set { SetPropertyValue<string>(nameof(TIP_DESTINO), ref fTIP_DESTINO, value); }
        }
        string fEST_VERIFICACION;
        [Size(1)]
        public string EST_VERIFICACION
        {
            get { return fEST_VERIFICACION; }
            set { SetPropertyValue<string>(nameof(EST_VERIFICACION), ref fEST_VERIFICACION, value); }
        }
        string fAUT_PENDIENTE;
        [Size(1)]
        public string AUT_PENDIENTE
        {
            get { return fAUT_PENDIENTE; }
            set { SetPropertyValue<string>(nameof(AUT_PENDIENTE), ref fAUT_PENDIENTE, value); }
        }
        string fNIV_APROBACION;
        [Size(3)]
        public string NIV_APROBACION
        {
            get { return fNIV_APROBACION; }
            set { SetPropertyValue<string>(nameof(NIV_APROBACION), ref fNIV_APROBACION, value); }
        }
        int fNRO_ACTA;
        public int NRO_ACTA
        {
            get { return fNRO_ACTA; }
            set { SetPropertyValue<int>(nameof(NRO_ACTA), ref fNRO_ACTA, value); }
        }
        short fCOD_BANCA;
        public short COD_BANCA
        {
            get { return fCOD_BANCA; }
            set { SetPropertyValue<short>(nameof(COD_BANCA), ref fCOD_BANCA, value); }
        }
        int fCOD_AUTORIZACION;
        public int COD_AUTORIZACION
        {
            get { return fCOD_AUTORIZACION; }
            set { SetPropertyValue<int>(nameof(COD_AUTORIZACION), ref fCOD_AUTORIZACION, value); }
        }
        decimal fPOR_ORI_FONDO;
        public decimal POR_ORI_FONDO
        {
            get { return fPOR_ORI_FONDO; }
            set { SetPropertyValue<decimal>(nameof(POR_ORI_FONDO), ref fPOR_ORI_FONDO, value); }
        }
        decimal fTOT_DESEMBOLSO;
        public decimal TOT_DESEMBOLSO
        {
            get { return fTOT_DESEMBOLSO; }
            set { SetPropertyValue<decimal>(nameof(TOT_DESEMBOLSO), ref fTOT_DESEMBOLSO, value); }
        }
        DateTime fFEC_REN_TASA;
        public DateTime FEC_REN_TASA
        {
            get { return fFEC_REN_TASA; }
            set { SetPropertyValue<DateTime>(nameof(FEC_REN_TASA), ref fFEC_REN_TASA, value); }
        }
        string fCOD_RUB_ECONOMICO;
        [Size(6)]
        public string COD_RUB_ECONOMICO
        {
            get { return fCOD_RUB_ECONOMICO; }
            set { SetPropertyValue<string>(nameof(COD_RUB_ECONOMICO), ref fCOD_RUB_ECONOMICO, value); }
        }
        string fOID;
        [Key]
        [Size(36)]
        public string OID
        {
            get { return fOID; }
            set { SetPropertyValue<string>(nameof(OID), ref fOID, value); }
        }
        string fID_SOLICITUD;
        [Size(36)]
        public string ID_SOLICITUD
        {
            get { return fID_SOLICITUD; }
            set { SetPropertyValue<string>(nameof(ID_SOLICITUD), ref fID_SOLICITUD, value); }
        }
        string fID_PERSONA;
        [Size(36)]
        public string ID_PERSONA
        {
            get { return fID_PERSONA; }
            set { SetPropertyValue<string>(nameof(ID_PERSONA), ref fID_PERSONA, value); }
        }
        string fPROCESADO;
        [Size(1)]
        public string PROCESADO
        {
            get { return fPROCESADO; }
            set { SetPropertyValue<string>(nameof(PROCESADO), ref fPROCESADO, value); }
        }
        byte fTIP_DES_ESPECIFICO;
        public byte TIP_DES_ESPECIFICO
        {
            get { return fTIP_DES_ESPECIFICO; }
            set { SetPropertyValue<byte>(nameof(TIP_DES_ESPECIFICO), ref fTIP_DES_ESPECIFICO, value); }
        }
        decimal fVAL_TASA;
        [ColumnDbDefaultValue("0 ")]
        public decimal VAL_TASA
        {
            get { return fVAL_TASA; }
            set { SetPropertyValue<decimal>(nameof(VAL_TASA), ref fVAL_TASA, value); }
        }
        string fTIP_COBRO;
        [Size(1)]
        [ColumnDbDefaultValue("'A'\n")]
        public string TIP_COBRO
        {
            get { return fTIP_COBRO; }
            set { SetPropertyValue<string>(nameof(TIP_COBRO), ref fTIP_COBRO, value); }
        }
        short fPER_VENCIMIENTO;
        public short PER_VENCIMIENTO
        {
            get { return fPER_VENCIMIENTO; }
            set { SetPropertyValue<short>(nameof(PER_VENCIMIENTO), ref fPER_VENCIMIENTO, value); }
        }
    }

}
