//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace IntegracionITGF.ITGFDataModel
{

    public partial class INT_PR_SOL_CUOTAS : XPLiteObject
    {
        int fNRO_SOLICITUD;
        public int NRO_SOLICITUD
        {
            get { return fNRO_SOLICITUD; }
            set { SetPropertyValue<int>(nameof(NRO_SOLICITUD), ref fNRO_SOLICITUD, value); }
        }
        byte fNRO_CUOTA;
        public byte NRO_CUOTA
        {
            get { return fNRO_CUOTA; }
            set { SetPropertyValue<byte>(nameof(NRO_CUOTA), ref fNRO_CUOTA, value); }
        }
        decimal fMTO_CAPITAL;
        [ColumnDbDefaultValue("0 ")]
        public decimal MTO_CAPITAL
        {
            get { return fMTO_CAPITAL; }
            set { SetPropertyValue<decimal>(nameof(MTO_CAPITAL), ref fMTO_CAPITAL, value); }
        }
        DateTime fFEC_VTO_HABIL;
        public DateTime FEC_VTO_HABIL
        {
            get { return fFEC_VTO_HABIL; }
            set { SetPropertyValue<DateTime>(nameof(FEC_VTO_HABIL), ref fFEC_VTO_HABIL, value); }
        }
        DateTime fFEC_VTO_EXACTO;
        public DateTime FEC_VTO_EXACTO
        {
            get { return fFEC_VTO_EXACTO; }
            set { SetPropertyValue<DateTime>(nameof(FEC_VTO_EXACTO), ref fFEC_VTO_EXACTO, value); }
        }
        decimal fVAL_INTERES;
        [ColumnDbDefaultValue("0")]
        public decimal VAL_INTERES
        {
            get { return fVAL_INTERES; }
            set { SetPropertyValue<decimal>(nameof(VAL_INTERES), ref fVAL_INTERES, value); }
        }
        decimal fSAL_CAPITAL;
        [ColumnDbDefaultValue("0")]
        public decimal SAL_CAPITAL
        {
            get { return fSAL_CAPITAL; }
            set { SetPropertyValue<decimal>(nameof(SAL_CAPITAL), ref fSAL_CAPITAL, value); }
        }
        decimal fSAL_CAP_ANTERIOR;
        [ColumnDbDefaultValue("0")]
        public decimal SAL_CAP_ANTERIOR
        {
            get { return fSAL_CAP_ANTERIOR; }
            set { SetPropertyValue<decimal>(nameof(SAL_CAP_ANTERIOR), ref fSAL_CAP_ANTERIOR, value); }
        }
        short fDIA_PERIODO;
        public short DIA_PERIODO
        {
            get { return fDIA_PERIODO; }
            set { SetPropertyValue<short>(nameof(DIA_PERIODO), ref fDIA_PERIODO, value); }
        }
        short fDIA_TRANSCURRIDOS;
        public short DIA_TRANSCURRIDOS
        {
            get { return fDIA_TRANSCURRIDOS; }
            set { SetPropertyValue<short>(nameof(DIA_TRANSCURRIDOS), ref fDIA_TRANSCURRIDOS, value); }
        }
        short fDIA_INTERES;
        public short DIA_INTERES
        {
            get { return fDIA_INTERES; }
            set { SetPropertyValue<short>(nameof(DIA_INTERES), ref fDIA_INTERES, value); }
        }
        string fTIP_CALCULO;
        [Size(1)]
        public string TIP_CALCULO
        {
            get { return fTIP_CALCULO; }
            set { SetPropertyValue<string>(nameof(TIP_CALCULO), ref fTIP_CALCULO, value); }
        }
        decimal fVAL_INT_ORIGINAL;
        [ColumnDbDefaultValue("0")]
        public decimal VAL_INT_ORIGINAL
        {
            get { return fVAL_INT_ORIGINAL; }
            set { SetPropertyValue<decimal>(nameof(VAL_INT_ORIGINAL), ref fVAL_INT_ORIGINAL, value); }
        }
        decimal fVAL_INT_ADELANTADO;
        [ColumnDbDefaultValue("0")]
        public decimal VAL_INT_ADELANTADO
        {
            get { return fVAL_INT_ADELANTADO; }
            set { SetPropertyValue<decimal>(nameof(VAL_INT_ADELANTADO), ref fVAL_INT_ADELANTADO, value); }
        }
        string fUSU_INSERCION;
        [Size(10)]
        [ColumnDbDefaultValue("SUBSTR(USER,1,10) ")]
        public string USU_INSERCION
        {
            get { return fUSU_INSERCION; }
            set { SetPropertyValue<string>(nameof(USU_INSERCION), ref fUSU_INSERCION, value); }
        }
        DateTime fFEC_INSERCION;
        [ColumnDbDefaultValue("SYSDATE ")]
        public DateTime FEC_INSERCION
        {
            get { return fFEC_INSERCION; }
            set { SetPropertyValue<DateTime>(nameof(FEC_INSERCION), ref fFEC_INSERCION, value); }
        }
        string fUSU_MODIFICACION;
        [Size(10)]
        [ColumnDbDefaultValue("SUBSTR(USER,1,10) ")]
        public string USU_MODIFICACION
        {
            get { return fUSU_MODIFICACION; }
            set { SetPropertyValue<string>(nameof(USU_MODIFICACION), ref fUSU_MODIFICACION, value); }
        }
        DateTime fFEC_MODIFICACION;
        [ColumnDbDefaultValue("SYSDATE ")]
        public DateTime FEC_MODIFICACION
        {
            get { return fFEC_MODIFICACION; }
            set { SetPropertyValue<DateTime>(nameof(FEC_MODIFICACION), ref fFEC_MODIFICACION, value); }
        }
        string fOID;
        [Key]
        [Size(36)]
        public string OID
        {
            get { return fOID; }
            set { SetPropertyValue<string>(nameof(OID), ref fOID, value); }
        }
        string fID_SOLICITUD;
        [Size(36)]
        public string ID_SOLICITUD
        {
            get { return fID_SOLICITUD; }
            set { SetPropertyValue<string>(nameof(ID_SOLICITUD), ref fID_SOLICITUD, value); }
        }
        string fID_CUOTA;
        [Size(36)]
        public string ID_CUOTA
        {
            get { return fID_CUOTA; }
            set { SetPropertyValue<string>(nameof(ID_CUOTA), ref fID_CUOTA, value); }
        }
        string fPROCESADO;
        [Size(1)]
        public string PROCESADO
        {
            get { return fPROCESADO; }
            set { SetPropertyValue<string>(nameof(PROCESADO), ref fPROCESADO, value); }
        }
    }

}
