//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace IntegracionITGF.ITGFDataModel
{

    public partial class INT_BA_DIRECCIONES : XPLiteObject
    {
        string fUSU_MODIFICACION;
        [Size(10)]
        [ColumnDbDefaultValue("SUBSTR(USER,1,10)")]
        public string USU_MODIFICACION
        {
            get { return fUSU_MODIFICACION; }
            set { SetPropertyValue<string>(nameof(USU_MODIFICACION), ref fUSU_MODIFICACION, value); }
        }
        DateTime fFEC_MODIFICACION;
        [ColumnDbDefaultValue("SYSDATE")]
        public DateTime FEC_MODIFICACION
        {
            get { return fFEC_MODIFICACION; }
            set { SetPropertyValue<DateTime>(nameof(FEC_MODIFICACION), ref fFEC_MODIFICACION, value); }
        }
        string fNUMERO;
        [Size(8)]
        public string NUMERO
        {
            get { return fNUMERO; }
            set { SetPropertyValue<string>(nameof(NUMERO), ref fNUMERO, value); }
        }
        string fDEPARTAMENTO;
        [Size(8)]
        public string DEPARTAMENTO
        {
            get { return fDEPARTAMENTO; }
            set { SetPropertyValue<string>(nameof(DEPARTAMENTO), ref fDEPARTAMENTO, value); }
        }
        string fPISO;
        [Size(8)]
        public string PISO
        {
            get { return fPISO; }
            set { SetPropertyValue<string>(nameof(PISO), ref fPISO, value); }
        }
        string fEDIFICIO;
        [Size(35)]
        public string EDIFICIO
        {
            get { return fEDIFICIO; }
            set { SetPropertyValue<string>(nameof(EDIFICIO), ref fEDIFICIO, value); }
        }
        string fCOD_POSTAL;
        [Size(10)]
        public string COD_POSTAL
        {
            get { return fCOD_POSTAL; }
            set { SetPropertyValue<string>(nameof(COD_POSTAL), ref fCOD_POSTAL, value); }
        }
        string fID_PERSONA;
        [Size(36)]
        public string ID_PERSONA
        {
            get { return fID_PERSONA; }
            set { SetPropertyValue<string>(nameof(ID_PERSONA), ref fID_PERSONA, value); }
        }

        string fOID;
        [Key]
        [Size(36)]
        public string OID
        {
            get { return fOID; }
            set { SetPropertyValue<string>(nameof(OID), ref fOID, value); }
        }
        string fCOD_PERSONA;
        [Size(10)]
        public string COD_PERSONA
        {
            get { return fCOD_PERSONA; }
            set { SetPropertyValue<string>(nameof(COD_PERSONA), ref fCOD_PERSONA, value); }
        }
        byte fCOD_DIRECCION;
        public byte COD_DIRECCION
        {
            get { return fCOD_DIRECCION; }
            set { SetPropertyValue<byte>(nameof(COD_DIRECCION), ref fCOD_DIRECCION, value); }
        }
        string fTIPO;
        [Size(1)]
        public string TIPO
        {
            get { return fTIPO; }
            set { SetPropertyValue<string>(nameof(TIPO), ref fTIPO, value); }
        }
        string fPRINCIPAL;
        [Size(1)]
        [ColumnDbDefaultValue("'N' ")]
        public string PRINCIPAL
        {
            get { return fPRINCIPAL; }
            set { SetPropertyValue<string>(nameof(PRINCIPAL), ref fPRINCIPAL, value); }
        }
        string fDIRECCION;
        [Size(80)]
        public string DIRECCION
        {
            get { return fDIRECCION; }
            set { SetPropertyValue<string>(nameof(DIRECCION), ref fDIRECCION, value); }
        }
        byte fCOD_PAIS;
        public byte COD_PAIS
        {
            get { return fCOD_PAIS; }
            set { SetPropertyValue<byte>(nameof(COD_PAIS), ref fCOD_PAIS, value); }
        }
        byte fCOD_CIUDAD;
        public byte COD_CIUDAD
        {
            get { return fCOD_CIUDAD; }
            set { SetPropertyValue<byte>(nameof(COD_CIUDAD), ref fCOD_CIUDAD, value); }
        }
        byte fCOD_BARRIO;
        public byte COD_BARRIO
        {
            get { return fCOD_BARRIO; }
            set { SetPropertyValue<byte>(nameof(COD_BARRIO), ref fCOD_BARRIO, value); }
        }
        string fOBSERVACION;
        [Size(1000)]
        public string OBSERVACION
        {
            get { return fOBSERVACION; }
            set { SetPropertyValue<string>(nameof(OBSERVACION), ref fOBSERVACION, value); }
        }
        string fUSU_INSERCION;
        [Size(10)]
        [ColumnDbDefaultValue("SUBSTR(USER,1,10)")]
        public string USU_INSERCION
        {
            get { return fUSU_INSERCION; }
            set { SetPropertyValue<string>(nameof(USU_INSERCION), ref fUSU_INSERCION, value); }
        }
        DateTime fFEC_INSERCION;
        [ColumnDbDefaultValue("SYSDATE")]
        public DateTime FEC_INSERCION
        {
            get { return fFEC_INSERCION; }
            set { SetPropertyValue<DateTime>(nameof(FEC_INSERCION), ref fFEC_INSERCION, value); }
        }
        string fID_DIRECCION;
        [Size(36)]
        public string ID_DIRECCION
        {
            get { return fID_DIRECCION; }
            set { SetPropertyValue<string>(nameof(ID_DIRECCION), ref fID_DIRECCION, value); }
        }
        string fPROCESADO;
        [Size(1)]
        [ColumnDbDefaultValue("'N' ")]
        public string PROCESADO
        {
            get { return fPROCESADO; }
            set { SetPropertyValue<string>(nameof(PROCESADO), ref fPROCESADO, value); }
        }
    }

}
