//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace IntegracionITGF.ITGFDataModel
{

    public partial class INT_BA_PERSONAS : XPLiteObject
    {
        string fCOD_PERSONA;
        [Size(10)]
        public string COD_PERSONA
        {
            get { return fCOD_PERSONA; }
            set { SetPropertyValue<string>(nameof(COD_PERSONA), ref fCOD_PERSONA, value); }
        }
        string fNOM_COMPLETO;
        [Size(120)]
        public string NOM_COMPLETO
        {
            get { return fNOM_COMPLETO; }
            set { SetPropertyValue<string>(nameof(NOM_COMPLETO), ref fNOM_COMPLETO, value); }
        }
        string fTIPO;
        [Size(1)]
        public string TIPO
        {
            get { return fTIPO; }
            set { SetPropertyValue<string>(nameof(TIPO), ref fTIPO, value); }
        }
        string fCOD_USU_PROMOTOR;
        [Size(10)]
        public string COD_USU_PROMOTOR
        {
            get { return fCOD_USU_PROMOTOR; }
            set { SetPropertyValue<string>(nameof(COD_USU_PROMOTOR), ref fCOD_USU_PROMOTOR, value); }
        }
        byte fCOD_TIP_DOCUMENTO;
        public byte COD_TIP_DOCUMENTO
        {
            get { return fCOD_TIP_DOCUMENTO; }
            set { SetPropertyValue<byte>(nameof(COD_TIP_DOCUMENTO), ref fCOD_TIP_DOCUMENTO, value); }
        }
        string fNRO_DOCUMENTO;
        [Size(20)]
        public string NRO_DOCUMENTO
        {
            get { return fNRO_DOCUMENTO; }
            set { SetPropertyValue<string>(nameof(NRO_DOCUMENTO), ref fNRO_DOCUMENTO, value); }
        }
        byte fCOD_PAIS;
        public byte COD_PAIS
        {
            get { return fCOD_PAIS; }
            set { SetPropertyValue<byte>(nameof(COD_PAIS), ref fCOD_PAIS, value); }
        }
        string fDIR_CORREO;
        [Size(80)]
        public string DIR_CORREO
        {
            get { return fDIR_CORREO; }
            set { SetPropertyValue<string>(nameof(DIR_CORREO), ref fDIR_CORREO, value); }
        }
        byte fCOD_ACTIVIDAD;
        public byte COD_ACTIVIDAD
        {
            get { return fCOD_ACTIVIDAD; }
            set { SetPropertyValue<byte>(nameof(COD_ACTIVIDAD), ref fCOD_ACTIVIDAD, value); }
        }
        decimal fTOT_INGRESOS;
        [ColumnDbDefaultValue("0")]
        public decimal TOT_INGRESOS
        {
            get { return fTOT_INGRESOS; }
            set { SetPropertyValue<decimal>(nameof(TOT_INGRESOS), ref fTOT_INGRESOS, value); }
        }
        decimal fING_PRESUNTOS;
        [ColumnDbDefaultValue("0")]
        public decimal ING_PRESUNTOS
        {
            get { return fING_PRESUNTOS; }
            set { SetPropertyValue<decimal>(nameof(ING_PRESUNTOS), ref fING_PRESUNTOS, value); }
        }
        decimal fEGR_PRESUNTOS;
        [ColumnDbDefaultValue("0")]
        public decimal EGR_PRESUNTOS
        {
            get { return fEGR_PRESUNTOS; }
            set { SetPropertyValue<decimal>(nameof(EGR_PRESUNTOS), ref fEGR_PRESUNTOS, value); }
        }
        string fUSU_INSERCION;
        [Size(10)]
        [ColumnDbDefaultValue("SUBSTR(USER,1,10)")]
        public string USU_INSERCION
        {
            get { return fUSU_INSERCION; }
            set { SetPropertyValue<string>(nameof(USU_INSERCION), ref fUSU_INSERCION, value); }
        }
        DateTime fFEC_INSERCION;
        [ColumnDbDefaultValue("SYSDATE")]
        public DateTime FEC_INSERCION
        {
            get { return fFEC_INSERCION; }
            set { SetPropertyValue<DateTime>(nameof(FEC_INSERCION), ref fFEC_INSERCION, value); }
        }
        string fUSU_MODIFICACION;
        [Size(10)]
        [ColumnDbDefaultValue("SUBSTR(USER,1,10)")]
        public string USU_MODIFICACION
        {
            get { return fUSU_MODIFICACION; }
            set { SetPropertyValue<string>(nameof(USU_MODIFICACION), ref fUSU_MODIFICACION, value); }
        }
        DateTime fFEC_MODIFICACION;
        [ColumnDbDefaultValue("SYSDATE")]
        public DateTime FEC_MODIFICACION
        {
            get { return fFEC_MODIFICACION; }
            set { SetPropertyValue<DateTime>(nameof(FEC_MODIFICACION), ref fFEC_MODIFICACION, value); }
        }
        string fEST_VERIFICACION;
        [Size(1)]
        [ColumnDbDefaultValue("'N'")]
        public string EST_VERIFICACION
        {
            get { return fEST_VERIFICACION; }
            set { SetPropertyValue<string>(nameof(EST_VERIFICACION), ref fEST_VERIFICACION, value); }
        }
        string fCOD_USU_VERIFICADOR;
        [Size(10)]
        public string COD_USU_VERIFICADOR
        {
            get { return fCOD_USU_VERIFICADOR; }
            set { SetPropertyValue<string>(nameof(COD_USU_VERIFICADOR), ref fCOD_USU_VERIFICADOR, value); }
        }
        string fNOM_PER_INFORMO;
        [Size(120)]
        public string NOM_PER_INFORMO
        {
            get { return fNOM_PER_INFORMO; }
            set { SetPropertyValue<string>(nameof(NOM_PER_INFORMO), ref fNOM_PER_INFORMO, value); }
        }
        string fOBS_VERIFICACION;
        [Size(1000)]
        public string OBS_VERIFICACION
        {
            get { return fOBS_VERIFICACION; }
            set { SetPropertyValue<string>(nameof(OBS_VERIFICACION), ref fOBS_VERIFICACION, value); }
        }
        DateTime fFEC_VERIFICACION;
        public DateTime FEC_VERIFICACION
        {
            get { return fFEC_VERIFICACION; }
            set { SetPropertyValue<DateTime>(nameof(FEC_VERIFICACION), ref fFEC_VERIFICACION, value); }
        }
        string fTIP_RELACION;
        [Size(1)]
        public string TIP_RELACION
        {
            get { return fTIP_RELACION; }
            set { SetPropertyValue<string>(nameof(TIP_RELACION), ref fTIP_RELACION, value); }
        }
        DateTime fFEC_VTO_DOCUMENTO;
        public DateTime FEC_VTO_DOCUMENTO
        {
            get { return fFEC_VTO_DOCUMENTO; }
            set { SetPropertyValue<DateTime>(nameof(FEC_VTO_DOCUMENTO), ref fFEC_VTO_DOCUMENTO, value); }
        }
        string fTIP_IVA;
        [Size(2)]
        [ColumnDbDefaultValue("'NC'")]
        public string TIP_IVA
        {
            get { return fTIP_IVA; }
            set { SetPropertyValue<string>(nameof(TIP_IVA), ref fTIP_IVA, value); }
        }
        string fTAS_PERSONALIZADA;
        [Size(1)]
        [ColumnDbDefaultValue("'N'")]
        public string TAS_PERSONALIZADA
        {
            get { return fTAS_PERSONALIZADA; }
            set { SetPropertyValue<string>(nameof(TAS_PERSONALIZADA), ref fTAS_PERSONALIZADA, value); }
        }
        string fRECIBE_SMS;
        [Size(1)]
        [ColumnDbDefaultValue("'S'")]
        public string RECIBE_SMS
        {
            get { return fRECIBE_SMS; }
            set { SetPropertyValue<string>(nameof(RECIBE_SMS), ref fRECIBE_SMS, value); }
        }
        string fCOD_RUB_PRIMARIO;
        [Size(6)]
        public string COD_RUB_PRIMARIO
        {
            get { return fCOD_RUB_PRIMARIO; }
            set { SetPropertyValue<string>(nameof(COD_RUB_PRIMARIO), ref fCOD_RUB_PRIMARIO, value); }
        }
        string fCOD_RUB_SECUNDARIO;
        [Size(6)]
        public string COD_RUB_SECUNDARIO
        {
            get { return fCOD_RUB_SECUNDARIO; }
            set { SetPropertyValue<string>(nameof(COD_RUB_SECUNDARIO), ref fCOD_RUB_SECUNDARIO, value); }
        }
        string fCOD_RUB_TERCIARIO;
        [Size(6)]
        public string COD_RUB_TERCIARIO
        {
            get { return fCOD_RUB_TERCIARIO; }
            set { SetPropertyValue<string>(nameof(COD_RUB_TERCIARIO), ref fCOD_RUB_TERCIARIO, value); }
        }
        int fCOD_GRUPO;
        public int COD_GRUPO
        {
            get { return fCOD_GRUPO; }
            set { SetPropertyValue<int>(nameof(COD_GRUPO), ref fCOD_GRUPO, value); }
        }
        string fEMP_NO_GENERADORA;
        [Size(1)]
        public string EMP_NO_GENERADORA
        {
            get { return fEMP_NO_GENERADORA; }
            set { SetPropertyValue<string>(nameof(EMP_NO_GENERADORA), ref fEMP_NO_GENERADORA, value); }
        }
        string fPRI_NOMBRE;
        [Size(30)]
        public string PRI_NOMBRE
        {
            get { return fPRI_NOMBRE; }
            set { SetPropertyValue<string>(nameof(PRI_NOMBRE), ref fPRI_NOMBRE, value); }
        }
        string fPRI_APELLIDO;
        [Size(30)]
        public string PRI_APELLIDO
        {
            get { return fPRI_APELLIDO; }
            set { SetPropertyValue<string>(nameof(PRI_APELLIDO), ref fPRI_APELLIDO, value); }
        }
        string fEST_CIVIL;
        [Size(1)]
        [ColumnDbDefaultValue("'S' ")]
        public string EST_CIVIL
        {
            get { return fEST_CIVIL; }
            set { SetPropertyValue<string>(nameof(EST_CIVIL), ref fEST_CIVIL, value); }
        }
        string fCOD_SEXO;
        [Size(1)]
        [ColumnDbDefaultValue("'M' ")]
        public string COD_SEXO
        {
            get { return fCOD_SEXO; }
            set { SetPropertyValue<string>(nameof(COD_SEXO), ref fCOD_SEXO, value); }
        }
        byte fCOD_NIV_ESTUDIO;
        public byte COD_NIV_ESTUDIO
        {
            get { return fCOD_NIV_ESTUDIO; }
            set { SetPropertyValue<byte>(nameof(COD_NIV_ESTUDIO), ref fCOD_NIV_ESTUDIO, value); }
        }
        byte fCOD_TIP_VIVIENDA;
        public byte COD_TIP_VIVIENDA
        {
            get { return fCOD_TIP_VIVIENDA; }
            set { SetPropertyValue<byte>(nameof(COD_TIP_VIVIENDA), ref fCOD_TIP_VIVIENDA, value); }
        }
        byte fCOD_PAI_NACIONALIDAD;
        public byte COD_PAI_NACIONALIDAD
        {
            get { return fCOD_PAI_NACIONALIDAD; }
            set { SetPropertyValue<byte>(nameof(COD_PAI_NACIONALIDAD), ref fCOD_PAI_NACIONALIDAD, value); }
        }
        string fSEG_NOMBRE;
        [Size(30)]
        public string SEG_NOMBRE
        {
            get { return fSEG_NOMBRE; }
            set { SetPropertyValue<string>(nameof(SEG_NOMBRE), ref fSEG_NOMBRE, value); }
        }
        string fSEG_APELLIDO;
        [Size(30)]
        public string SEG_APELLIDO
        {
            get { return fSEG_APELLIDO; }
            set { SetPropertyValue<string>(nameof(SEG_APELLIDO), ref fSEG_APELLIDO, value); }
        }
        DateTime fFEC_NACIMIENTO;
        public DateTime FEC_NACIMIENTO
        {
            get { return fFEC_NACIMIENTO; }
            set { SetPropertyValue<DateTime>(nameof(FEC_NACIMIENTO), ref fFEC_NACIMIENTO, value); }
        }
        byte fCAN_HIJOS;
        public byte CAN_HIJOS
        {
            get { return fCAN_HIJOS; }
            set { SetPropertyValue<byte>(nameof(CAN_HIJOS), ref fCAN_HIJOS, value); }
        }
        byte fCOD_PROFESION;
        public byte COD_PROFESION
        {
            get { return fCOD_PROFESION; }
            set { SetPropertyValue<byte>(nameof(COD_PROFESION), ref fCOD_PROFESION, value); }
        }
        string fRAZ_SOCIAL;
        [Size(120)]
        public string RAZ_SOCIAL
        {
            get { return fRAZ_SOCIAL; }
            set { SetPropertyValue<string>(nameof(RAZ_SOCIAL), ref fRAZ_SOCIAL, value); }
        }
        string fNOM_COMERCIAL;
        [Size(65)]
        public string NOM_COMERCIAL
        {
            get { return fNOM_COMERCIAL; }
            set { SetPropertyValue<string>(nameof(NOM_COMERCIAL), ref fNOM_COMERCIAL, value); }
        }
        string fNATURALEZA;
        [Size(20)]
        public string NATURALEZA
        {
            get { return fNATURALEZA; }
            set { SetPropertyValue<string>(nameof(NATURALEZA), ref fNATURALEZA, value); }
        }
        DateTime fFEC_APERTURA;
        public DateTime FEC_APERTURA
        {
            get { return fFEC_APERTURA; }
            set { SetPropertyValue<DateTime>(nameof(FEC_APERTURA), ref fFEC_APERTURA, value); }
        }
        byte fCOD_RAMO;
        public byte COD_RAMO
        {
            get { return fCOD_RAMO; }
            set { SetPropertyValue<byte>(nameof(COD_RAMO), ref fCOD_RAMO, value); }
        }
        string fGAR_TERCERO;
        [Size(1)]
        public string GAR_TERCERO
        {
            get { return fGAR_TERCERO; }
            set { SetPropertyValue<string>(nameof(GAR_TERCERO), ref fGAR_TERCERO, value); }
        }
        decimal fCAP_OPERATIVO;
        public decimal CAP_OPERATIVO
        {
            get { return fCAP_OPERATIVO; }
            set { SetPropertyValue<decimal>(nameof(CAP_OPERATIVO), ref fCAP_OPERATIVO, value); }
        }
        string fCOD_AREA;
        [Size(5)]
        public string COD_AREA
        {
            get { return fCOD_AREA; }
            set { SetPropertyValue<string>(nameof(COD_AREA), ref fCOD_AREA, value); }
        }
        byte fCOD_OFICINA;
        public byte COD_OFICINA
        {
            get { return fCOD_OFICINA; }
            set { SetPropertyValue<byte>(nameof(COD_OFICINA), ref fCOD_OFICINA, value); }
        }
        string fCAT_RIESGO;
        [Size(1)]
        public string CAT_RIESGO
        {
            get { return fCAT_RIESGO; }
            set { SetPropertyValue<string>(nameof(CAT_RIESGO), ref fCAT_RIESGO, value); }
        }
        byte fCOD_GRU_ECONOMICO;
        public byte COD_GRU_ECONOMICO
        {
            get { return fCOD_GRU_ECONOMICO; }
            set { SetPropertyValue<byte>(nameof(COD_GRU_ECONOMICO), ref fCOD_GRU_ECONOMICO, value); }
        }
        string fEXO_IMPUESTOS;
        [Size(1)]
        [ColumnDbDefaultValue("'N' ")]
        public string EXO_IMPUESTOS
        {
            get { return fEXO_IMPUESTOS; }
            set { SetPropertyValue<string>(nameof(EXO_IMPUESTOS), ref fEXO_IMPUESTOS, value); }
        }
        string fCOD_USU_OFICIAL;
        [Size(10)]
        public string COD_USU_OFICIAL
        {
            get { return fCOD_USU_OFICIAL; }
            set { SetPropertyValue<string>(nameof(COD_USU_OFICIAL), ref fCOD_USU_OFICIAL, value); }
        }
        string fCLI_ESPECIAL;
        [Size(1)]
        [ColumnDbDefaultValue("'N' ")]
        public string CLI_ESPECIAL
        {
            get { return fCLI_ESPECIAL; }
            set { SetPropertyValue<string>(nameof(CLI_ESPECIAL), ref fCLI_ESPECIAL, value); }
        }
        string fRESIDENTE;
        [Size(1)]
        [ColumnDbDefaultValue("'N' ")]
        public string RESIDENTE
        {
            get { return fRESIDENTE; }
            set { SetPropertyValue<string>(nameof(RESIDENTE), ref fRESIDENTE, value); }
        }
        string fCOD_SEC_CONTABLE;
        [Size(1)]
        public string COD_SEC_CONTABLE
        {
            get { return fCOD_SEC_CONTABLE; }
            set { SetPropertyValue<string>(nameof(COD_SEC_CONTABLE), ref fCOD_SEC_CONTABLE, value); }
        }
        byte fCOD_TIP_DEUDOR;
        public byte COD_TIP_DEUDOR
        {
            get { return fCOD_TIP_DEUDOR; }
            set { SetPropertyValue<byte>(nameof(COD_TIP_DEUDOR), ref fCOD_TIP_DEUDOR, value); }
        }
        byte fCOD_DEPARTAMENTO;
        public byte COD_DEPARTAMENTO
        {
            get { return fCOD_DEPARTAMENTO; }
            set { SetPropertyValue<byte>(nameof(COD_DEPARTAMENTO), ref fCOD_DEPARTAMENTO, value); }
        }
        decimal fNIV_CRUZAMIENTO;
        public decimal NIV_CRUZAMIENTO
        {
            get { return fNIV_CRUZAMIENTO; }
            set { SetPropertyValue<decimal>(nameof(NIV_CRUZAMIENTO), ref fNIV_CRUZAMIENTO, value); }
        }
        string fGE_CLIENTE_TIPO;
        [Size(1)]
        public string GE_CLIENTE_TIPO
        {
            get { return fGE_CLIENTE_TIPO; }
            set { SetPropertyValue<string>(nameof(GE_CLIENTE_TIPO), ref fGE_CLIENTE_TIPO, value); }
        }
        decimal fTOT_DEU_REAL;
        [ColumnDbDefaultValue("0")]
        public decimal TOT_DEU_REAL
        {
            get { return fTOT_DEU_REAL; }
            set { SetPropertyValue<decimal>(nameof(TOT_DEU_REAL), ref fTOT_DEU_REAL, value); }
        }
        decimal fTOT_DEU_CONTINGENTE;
        [ColumnDbDefaultValue("0")]
        public decimal TOT_DEU_CONTINGENTE
        {
            get { return fTOT_DEU_CONTINGENTE; }
            set { SetPropertyValue<decimal>(nameof(TOT_DEU_CONTINGENTE), ref fTOT_DEU_CONTINGENTE, value); }
        }
        bool fCAT_SUBJETIVA;
        public bool CAT_SUBJETIVA
        {
            get { return fCAT_SUBJETIVA; }
            set { SetPropertyValue<bool>(nameof(CAT_SUBJETIVA), ref fCAT_SUBJETIVA, value); }
        }
        decimal fTOT_GAR_COMPUTABLES;
        [ColumnDbDefaultValue("0")]
        public decimal TOT_GAR_COMPUTABLES
        {
            get { return fTOT_GAR_COMPUTABLES; }
            set { SetPropertyValue<decimal>(nameof(TOT_GAR_COMPUTABLES), ref fTOT_GAR_COMPUTABLES, value); }
        }
        decimal fTOT_PREVISION;
        [ColumnDbDefaultValue("0")]
        public decimal TOT_PREVISION
        {
            get { return fTOT_PREVISION; }
            set { SetPropertyValue<decimal>(nameof(TOT_PREVISION), ref fTOT_PREVISION, value); }
        }
        string fTIP_EXTRACTO;
        [Size(1)]
        [ColumnDbDefaultValue("'C' ")]
        public string TIP_EXTRACTO
        {
            get { return fTIP_EXTRACTO; }
            set { SetPropertyValue<string>(nameof(TIP_EXTRACTO), ref fTIP_EXTRACTO, value); }
        }
        string fCOD_USU_GESTION;
        [Size(10)]
        public string COD_USU_GESTION
        {
            get { return fCOD_USU_GESTION; }
            set { SetPropertyValue<string>(nameof(COD_USU_GESTION), ref fCOD_USU_GESTION, value); }
        }
        DateTime fFEC_INGRESO;
        [ColumnDbDefaultValue("TRUNC(SYSDATE) ")]
        public DateTime FEC_INGRESO
        {
            get { return fFEC_INGRESO; }
            set { SetPropertyValue<DateTime>(nameof(FEC_INGRESO), ref fFEC_INGRESO, value); }
        }
        byte fCOD_SEG_CLIENTE;
        public byte COD_SEG_CLIENTE
        {
            get { return fCOD_SEG_CLIENTE; }
            set { SetPropertyValue<byte>(nameof(COD_SEG_CLIENTE), ref fCOD_SEG_CLIENTE, value); }
        }
        string fCLI_CONFIDENCIAL;
        [Size(1)]
        [ColumnDbDefaultValue("'N' ")]
        public string CLI_CONFIDENCIAL
        {
            get { return fCLI_CONFIDENCIAL; }
            set { SetPropertyValue<string>(nameof(CLI_CONFIDENCIAL), ref fCLI_CONFIDENCIAL, value); }
        }
        decimal fTOT_DEU_SISTEMA;
        public decimal TOT_DEU_SISTEMA
        {
            get { return fTOT_DEU_SISTEMA; }
            set { SetPropertyValue<decimal>(nameof(TOT_DEU_SISTEMA), ref fTOT_DEU_SISTEMA, value); }
        }
        decimal fCAT_AUTOMATICA;
        [ColumnDbDefaultValue("1 ")]
        public decimal CAT_AUTOMATICA
        {
            get { return fCAT_AUTOMATICA; }
            set { SetPropertyValue<decimal>(nameof(CAT_AUTOMATICA), ref fCAT_AUTOMATICA, value); }
        }
        bool fCAT_SISTEMA;
        public bool CAT_SISTEMA
        {
            get { return fCAT_SISTEMA; }
            set { SetPropertyValue<bool>(nameof(CAT_SISTEMA), ref fCAT_SISTEMA, value); }
        }
        bool fCAT_RENOVACIONES;
        public bool CAT_RENOVACIONES
        {
            get { return fCAT_RENOVACIONES; }
            set { SetPropertyValue<bool>(nameof(CAT_RENOVACIONES), ref fCAT_RENOVACIONES, value); }
        }
        decimal fCAT_GRU_ECONOMICO;
        public decimal CAT_GRU_ECONOMICO
        {
            get { return fCAT_GRU_ECONOMICO; }
            set { SetPropertyValue<decimal>(nameof(CAT_GRU_ECONOMICO), ref fCAT_GRU_ECONOMICO, value); }
        }
        decimal fCAT_ANTERIOR;
        public decimal CAT_ANTERIOR
        {
            get { return fCAT_ANTERIOR; }
            set { SetPropertyValue<decimal>(nameof(CAT_ANTERIOR), ref fCAT_ANTERIOR, value); }
        }
        DateTime fFEC_CAT_ANTERIOR;
        public DateTime FEC_CAT_ANTERIOR
        {
            get { return fFEC_CAT_ANTERIOR; }
            set { SetPropertyValue<DateTime>(nameof(FEC_CAT_ANTERIOR), ref fFEC_CAT_ANTERIOR, value); }
        }
        DateTime fFEC_ULT_CLASIF;
        public DateTime FEC_ULT_CLASIF
        {
            get { return fFEC_ULT_CLASIF; }
            set { SetPropertyValue<DateTime>(nameof(FEC_ULT_CLASIF), ref fFEC_ULT_CLASIF, value); }
        }
        decimal fTOT_DEU_COD_SISTEMA;
        public decimal TOT_DEU_COD_SISTEMA
        {
            get { return fTOT_DEU_COD_SISTEMA; }
            set { SetPropertyValue<decimal>(nameof(TOT_DEU_COD_SISTEMA), ref fTOT_DEU_COD_SISTEMA, value); }
        }
        decimal fTOT_DEU_CODEUDORIA;
        public decimal TOT_DEU_CODEUDORIA
        {
            get { return fTOT_DEU_CODEUDORIA; }
            set { SetPropertyValue<decimal>(nameof(TOT_DEU_CODEUDORIA), ref fTOT_DEU_CODEUDORIA, value); }
        }
        decimal fTOT_DEU_CON_SISTEMA;
        public decimal TOT_DEU_CON_SISTEMA
        {
            get { return fTOT_DEU_CON_SISTEMA; }
            set { SetPropertyValue<decimal>(nameof(TOT_DEU_CON_SISTEMA), ref fTOT_DEU_CON_SISTEMA, value); }
        }
        string fULT_CAT_RIESGO;
        [Size(1)]
        public string ULT_CAT_RIESGO
        {
            get { return fULT_CAT_RIESGO; }
            set { SetPropertyValue<string>(nameof(ULT_CAT_RIESGO), ref fULT_CAT_RIESGO, value); }
        }
        string fCOD_PERFIL;
        [Size(20)]
        public string COD_PERFIL
        {
            get { return fCOD_PERFIL; }
            set { SetPropertyValue<string>(nameof(COD_PERFIL), ref fCOD_PERFIL, value); }
        }
        DateTime fFEC_ULT_ACCESO;
        public DateTime FEC_ULT_ACCESO
        {
            get { return fFEC_ULT_ACCESO; }
            set { SetPropertyValue<DateTime>(nameof(FEC_ULT_ACCESO), ref fFEC_ULT_ACCESO, value); }
        }
        decimal fCAT_PONDERADA;
        public decimal CAT_PONDERADA
        {
            get { return fCAT_PONDERADA; }
            set { SetPropertyValue<decimal>(nameof(CAT_PONDERADA), ref fCAT_PONDERADA, value); }
        }
        byte fCOD_CANAL;
        public byte COD_CANAL
        {
            get { return fCOD_CANAL; }
            set { SetPropertyValue<byte>(nameof(COD_CANAL), ref fCOD_CANAL, value); }
        }
        DateTime fFEC_CAT_SUBJETIVA;
        public DateTime FEC_CAT_SUBJETIVA
        {
            get { return fFEC_CAT_SUBJETIVA; }
            set { SetPropertyValue<DateTime>(nameof(FEC_CAT_SUBJETIVA), ref fFEC_CAT_SUBJETIVA, value); }
        }
        byte fMOT_CAT_SUBJETIVA;
        public byte MOT_CAT_SUBJETIVA
        {
            get { return fMOT_CAT_SUBJETIVA; }
            set { SetPropertyValue<byte>(nameof(MOT_CAT_SUBJETIVA), ref fMOT_CAT_SUBJETIVA, value); }
        }
        string fID_PERSONA;
        [Size(36)]
        public string ID_PERSONA
        {
            get { return fID_PERSONA; }
            set { SetPropertyValue<string>(nameof(ID_PERSONA), ref fID_PERSONA, value); }
        }
        string fOID;
        [Key]
        [Size(36)]
        public string OID
        {
            get { return fOID; }
            set { SetPropertyValue<string>(nameof(OID), ref fOID, value); }
        }
        string fPROCESADO;
        [Size(1)]
        [ColumnDbDefaultValue("'N'\n")]
        public string PROCESADO
        {
            get { return fPROCESADO; }
            set { SetPropertyValue<string>(nameof(PROCESADO), ref fPROCESADO, value); }
        }
    }

}
