//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PDNOriginacion.Module.PDNService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="PDNService.IExperto")]
    public interface IExperto {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IExperto/PDN_ConsultaExperto", ReplyAction="http://tempuri.org/IExperto/PDN_ConsultaExpertoResponse")]
        string PDN_ConsultaExperto(string xsUsuario, string xsPassword, string xsProducto, string xsModelo, string xsXml, string xsActDat);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IExperto/PDN_ConsultaExperto", ReplyAction="http://tempuri.org/IExperto/PDN_ConsultaExpertoResponse")]
        System.Threading.Tasks.Task<string> PDN_ConsultaExpertoAsync(string xsUsuario, string xsPassword, string xsProducto, string xsModelo, string xsXml, string xsActDat);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IExperto/PDN_GetModelos", ReplyAction="http://tempuri.org/IExperto/PDN_GetModelosResponse")]
        string PDN_GetModelos(string xsUsuario, string xsPassword);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IExperto/PDN_GetModelos", ReplyAction="http://tempuri.org/IExperto/PDN_GetModelosResponse")]
        System.Threading.Tasks.Task<string> PDN_GetModelosAsync(string xsUsuario, string xsPassword);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IExperto/PDN_GetDatosEquifax", ReplyAction="http://tempuri.org/IExperto/PDN_GetDatosEquifaxResponse")]
        string PDN_GetDatosEquifax(string xsUsuario, string xsPassword, string codServicio, string idConsulta, string variable);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IExperto/PDN_GetDatosEquifax", ReplyAction="http://tempuri.org/IExperto/PDN_GetDatosEquifaxResponse")]
        System.Threading.Tasks.Task<string> PDN_GetDatosEquifaxAsync(string xsUsuario, string xsPassword, string codServicio, string idConsulta, string variable);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IExpertoChannel : PDNOriginacion.Module.PDNService.IExperto, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ExpertoClient : System.ServiceModel.ClientBase<PDNOriginacion.Module.PDNService.IExperto>, PDNOriginacion.Module.PDNService.IExperto {
        
        public ExpertoClient() {
        }
        
        public ExpertoClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ExpertoClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ExpertoClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ExpertoClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string PDN_ConsultaExperto(string xsUsuario, string xsPassword, string xsProducto, string xsModelo, string xsXml, string xsActDat) {
            return base.Channel.PDN_ConsultaExperto(xsUsuario, xsPassword, xsProducto, xsModelo, xsXml, xsActDat);
        }
        
        public System.Threading.Tasks.Task<string> PDN_ConsultaExpertoAsync(string xsUsuario, string xsPassword, string xsProducto, string xsModelo, string xsXml, string xsActDat) {
            return base.Channel.PDN_ConsultaExpertoAsync(xsUsuario, xsPassword, xsProducto, xsModelo, xsXml, xsActDat);
        }
        
        public string PDN_GetModelos(string xsUsuario, string xsPassword) {
            return base.Channel.PDN_GetModelos(xsUsuario, xsPassword);
        }
        
        public System.Threading.Tasks.Task<string> PDN_GetModelosAsync(string xsUsuario, string xsPassword) {
            return base.Channel.PDN_GetModelosAsync(xsUsuario, xsPassword);
        }
        
        public string PDN_GetDatosEquifax(string xsUsuario, string xsPassword, string codServicio, string idConsulta, string variable) {
            return base.Channel.PDN_GetDatosEquifax(xsUsuario, xsPassword, codServicio, idConsulta, variable);
        }
        
        public System.Threading.Tasks.Task<string> PDN_GetDatosEquifaxAsync(string xsUsuario, string xsPassword, string codServicio, string idConsulta, string variable) {
            return base.Channel.PDN_GetDatosEquifaxAsync(xsUsuario, xsPassword, codServicio, idConsulta, variable);
        }
    }
}
