//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.CodeDom.Compiler;
using System.Diagnostics;
using System.ServiceModel;
using System.ServiceModel.Channels;
using System.Threading.Tasks;

namespace PDNOriginacion.Module.CKImportador
{
    [GeneratedCode("System.ServiceModel", "4.0.0.0")]
    [ServiceContract(ConfigurationName = "CKImportador.IImportService")]
    public interface IImportService
    {
        [OperationContract(Action = "http://tempuri.org/IImportService/Client_CreateOrUpdate", ReplyAction = "http://tempuri.org/IImportService/Client_CreateOrUpdateResponse")]
        string Client_CreateOrUpdate(string AppToken, string Operator, string Password, string xmlDatos);
        [OperationContract(Action = "http://tempuri.org/IImportService/Client_CreateOrUpdate", ReplyAction = "http://tempuri.org/IImportService/Client_CreateOrUpdateResponse")]
        Task<string> Client_CreateOrUpdateAsync(string AppToken, string Operator, string Password, string xmlDatos);
        [OperationContract(Action = "http://tempuri.org/IImportService/ClientLink_CreateOrUpdate", ReplyAction = "http://tempuri.org/IImportService/ClientLink_CreateOrUpdateResponse")]
        string ClientLink_CreateOrUpdate(string AppToken, string Operator, string Password, string xmlDatos);
        [OperationContract(Action = "http://tempuri.org/IImportService/ClientLink_CreateOrUpdate", ReplyAction = "http://tempuri.org/IImportService/ClientLink_CreateOrUpdateResponse")]
        Task<string> ClientLink_CreateOrUpdateAsync(string AppToken, string Operator, string Password, string xmlDatos);
        [OperationContract(Action = "http://tempuri.org/IImportService/Product_CreateOrUpdate", ReplyAction = "http://tempuri.org/IImportService/Product_CreateOrUpdateResponse")]
        string Product_CreateOrUpdate(string AppToken, string Operator, string Password, string xmlDatos);
        [OperationContract(Action = "http://tempuri.org/IImportService/Product_CreateOrUpdate", ReplyAction = "http://tempuri.org/IImportService/Product_CreateOrUpdateResponse")]
        Task<string> Product_CreateOrUpdateAsync(string AppToken, string Operator, string Password, string xmlDatos);
    }

    [GeneratedCode("System.ServiceModel", "4.0.0.0")]
    public interface IImportServiceChannel : IImportService, IClientChannel
    {
    }

    [DebuggerStepThrough]
    [GeneratedCode("System.ServiceModel", "4.0.0.0")]
    public partial class ImportServiceClient : ClientBase<IImportService>, IImportService
    {
        public ImportServiceClient()
        {
        }
        public ImportServiceClient(string endpointConfigurationName) : base(endpointConfigurationName)
        {
        }
        public ImportServiceClient(string endpointConfigurationName, string remoteAddress) : base(endpointConfigurationName,
                                                                                                  remoteAddress)
        {
        }
        public ImportServiceClient(string endpointConfigurationName, EndpointAddress remoteAddress) : base(endpointConfigurationName,
                                                                                                           remoteAddress)
        {
        }
        public ImportServiceClient(Binding binding, EndpointAddress remoteAddress) : base(binding, remoteAddress)
        {
        }

        public string Client_CreateOrUpdate(string AppToken, string Operator, string Password, string xmlDatos) => base.Channel
            .Client_CreateOrUpdate(AppToken, Operator, Password, xmlDatos);
        public Task<string> Client_CreateOrUpdateAsync(string AppToken,
                                                       string Operator,
                                                       string Password,
                                                       string xmlDatos) => base.Channel
            .Client_CreateOrUpdateAsync(AppToken, Operator, Password, xmlDatos);
        public string ClientLink_CreateOrUpdate(string AppToken, string Operator, string Password, string xmlDatos) => base.Channel
            .ClientLink_CreateOrUpdate(AppToken, Operator, Password, xmlDatos);
        public Task<string> ClientLink_CreateOrUpdateAsync(string AppToken,
                                                           string Operator,
                                                           string Password,
                                                           string xmlDatos) => base.Channel
            .ClientLink_CreateOrUpdateAsync(AppToken, Operator, Password, xmlDatos);
        public string Product_CreateOrUpdate(string AppToken, string Operator, string Password, string xmlDatos) => base.Channel
            .Product_CreateOrUpdate(AppToken, Operator, Password, xmlDatos);
        public Task<string> Product_CreateOrUpdateAsync(string AppToken,
                                                        string Operator,
                                                        string Password,
                                                        string xmlDatos) => base.Channel
            .Product_CreateOrUpdateAsync(AppToken, Operator, Password, xmlDatos);
    }
}
